### ISSUE TITLE
No Device found: Arduino Nano V3.0

### ISSUE THREAD

**Issue by cracker0dks** [mik3y/usb-serial-for-android#102]
Hey, 
why does the example app dont show me my Arduino Nano V3.0 ? (0 devices found)
Im using a samsung galaxy s2 and the App "USB Host Controller" shows me an USB2.0-Serial device. 

I debuged it and the problem ist, that there are no drivers found for this device. (availableDrivers.isEmpty() is true)

Can anyone help ?
thanks :)

EDIT: I tried to add the device by hand: 

customTable.addProduct(0x1a86, 0x7523, CdcAcmSerialDriver.class);

but  I get an index out of bounds excpetion on CdcAcmSerialDriver.java:122.
122: mDataInterface = mDevice.getInterface(1);

**Comment by MRodriguess** [comment]
Hi I'm having the same problem with arduino uno. Did you managed to get any solution for that exception?

**Comment by cracker0dks** [comment]
nop not yet... :(

**Comment by MRodriguess** [comment]
Thanks..I will let you know if I found some solution for my case. Might help you.

**Comment by cracker0dks** [comment]
that would be great. thanks !

**Comment by MRodriguess** [comment]
Well I made some progress. At least for Arduino UNO I managed to get it pass trough that exception by adding it manually to the costumProbeTable. this.

    // Create a costumProbeTable based on the defaultProbeTable
    ProbeTable costumProbeTable = UsbSerialProber.getDefaultProbeTable();

And then add the device info
    costumProbeTable.addProduct(arduino.VID(), arduino.PID(), CdcAcmSerialDriver.class);

finally
    List<UsbSerialDriver> availableDrivers =           UsbSerialProber.getProber(costumProbeTable).findAllDrivers(mManager);


and loop that list to search for the driver, of if that's the only one you are using, get the first. Then initialize the connection.

It passed trough the initialization, but when I send some data from the arduino. It breaks and the USBRequestJNI goes crazy with close init close init .... and I can't get the data. I'm done for today. I will try tomorrow to investigate a bit more.

**Comment by MRodriguess** [comment]
Hi cracker0DKS I have my arduino UNO working with android 4.03, using this library. I have updated the file CdcAcmSerialDriver to the last version and it worked. Are you using the last version?

**Comment by cracker0dks** [comment]
29 Days ago i used the last version. glad that it worked for u now. I will try this if I can. Thanks :+1:

**Comment by defvs** [comment]
Are you using an original arduino with an FTDI chip, or a clone with CH340G ? The latter isn't yet supported (see #194 )

Some more infos on differences between the two in #107

**Comment by kai-morich** [comment]
CH340 is supported. The PRs mentioned in #194 are merged
