### ISSUE TITLE
Error importing com.hoho.android.usbserial.driver

### ISSUE THREAD

**Issue by thiagobarbosa** [mik3y/usb-serial-for-android#104]
Hi guys,
I'm getting the error "The import com.hoho.android.usbserial.driver cannot be resolved". It is usually a dummie mistake, but I'm really stucked on that =/
Any help?

**Comment by BlueDraeth** [comment]
Hi guys i really have the same Problem can somebody help us?

**Comment by kai-morich** [comment]
instead if importing source into your project you can now consume the library as gradle dependency
