### ISSUE TITLE
App can read from USB but has writing problems

### ISSUE THREAD

**Issue by andremacpereira** [mik3y/usb-serial-for-android#109]
I need to write several times repeatedly in order to send a single USB command of 8 bytes.

What could I possibly be missing?

Is there any writing example for CDC/ACM?

**Comment by sureshjoshi** [comment]
Any luck with this?

**Comment by sureshjoshi** [comment]
So, I was having a lot of trouble here, and flipping the endpoints and such, my device never seemed to be receiving data.

I tried the Physicaloid library (https://github.com/ksksue/PhysicaloidLibrary) and was able to get reading/writing working correctly. If I get some time (I know this won't be soon), I'm going to hook up a USB monitor and see what's up with the CDCACM endpoints.

**Comment by kai-morich** [comment]
for various CDC/ACM devices like arduino you should set DTR+RTS
