### ISSUE TITLE
Five Devices are Tested

### ISSUE THREAD

**Issue by HJFang** [mik3y/usb-serial-for-android#119]
With the help of this opening resource, I have completed a project which need communication between Android and CP2103 device. During the development, 5 devices are tested and the result are as follows:
1. Huawei Honor H60 L02  ---------   Support
2. Google Nexus 7 Generation 2   ---------   Support
3. Huawei T1-821w   ----------  Support
4. Huawei Honor H30   --------- Don't Support (Don't Support OTG)
5. Samsung iTop-4412   ---------   Don't Support (Have not found the reason)
Hope this open source provide more convenience to developers.

**Comment by mik3y** [comment]
Thanks!
