### ISSUE TITLE
why data read in 11Byte packets

### ISSUE THREAD

**Issue by BabakArtApps** [mik3y/usb-serial-for-android#123]
I use PL2303HXD and write a android application. I write for Example 15  byte with write method and I connect RX with TX so I can get my output as input, but when the output sets to my text view its a 11 byte character an a 4 character.
how can I solve this

**Comment by mik3y** [comment]
Please see [troubleshooting topic](https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#when-reading-a-message-why-dont-all-bytes-arrive-at-the-same-time).
