### ISSUE TITLE
SerialInputOutputManager.Listener BufferSize for onNewData

### ISSUE THREAD

**Issue by barisozanguler** [mik3y/usb-serial-for-android#128]
Hi,

I'm communicating via CP210x usb device.

I want to change read each time 1 byte (BufferSize) for listener.   

```
private final SerialInputOutputManager.Listener mListener =
            new SerialInputOutputManager.Listener() {

                @Override
                public void onRunError(Exception e) {
                    Log.d(TAG, "Runner stopped.");
                }

                @Override
                public void onNewData(final byte[] data) {

                }


            };
```

How can i do that ? 

Thanks.

**Comment by fghjhuang** [comment]
i am looking for a way too,did u solve this problem?

**Comment by barisozanguler** [comment]
No man. I'm process each byte with for loop. :( I was tried configurate somethings in library code but its not work.

**Comment by fghjhuang** [comment]
ths anyway, i am doing it in a loop ,too

**Comment by kai-morich** [comment]
the SerialInputOutputManager reads all available data, then you can split the data in a loop, as you also suggested
