### ISSUE TITLE
How to import this library in android studio?

### ISSUE THREAD

**Issue by XSparter** [mik3y/usb-serial-for-android#129]

**Comment by aruntej** [comment]
Did you have any luck with importing this library to android studio

**Comment by XSparter** [comment]
No... But i have maked a serial conenction in android.

**Comment by Mushtaq123** [comment]
By Clicking Import Module by **File --> New-->Import Module** then Browse to your Library Project and Import

**Comment by atrvicky** [comment]
After importing as @Mushtaq123 said, include this in Gradle and sync files
compile project(':usbSerialForAndroid')

**Comment by Harin-Kaklotar** [comment]
download this project

open your android studio project

File > New > Import Module > set path of **usbSerialForAndroid** > Finish

**Comment by rsc9421** [comment]
I have this error
Error:Application and test application id cannot be the same: both are 'com.hoho.android.usbserial.examples' for debugAndroidTest

**Comment by buyukyukselburak** [comment]
I have this error
Error:Application and test application id cannot be the same: both are 'com.hoho.android.usbserial.examples' for debugAndroidTest
++

**Comment by kai-morich** [comment]
please try with commenting out 'testApplicationId ...' in usbSerialExamples/build.gradle

**Comment by alkocher** [comment]
Android Studio does not see the module

**Comment by jjavierk** [comment]
1. Create your project, 
2. Then, File -> New -> Import Module and add the path of the folder usbSerialForAndroid.
3. Open settings.gradle and add to the include ':usbSerialForAndroid'
4. Open Modular settings (right click on app folder), 
5. Go to the Dependencies tab, click on the green '+' symbol -> Module dependency.
6. If you have done everything correctly, usbSerialForAndroid will be listed already, select it and press ok.
Check the image for the steps.
![howto](https://user-images.githubusercontent.com/20179288/45584587-bab90580-b8d6-11e8-8d74-380320469057.png)

**Comment by uklertis** [comment]
I have the same issue with @XSparter. Has anybody solved it?

**Comment by kai-morich** [comment]
instead of importing the source in your project you can use gradle dependency as shown in README
