### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#131]
Make a new release & upload to maven.

**Comment by RePeet13** [comment]
Do you have an eta on this? I have no notion how easy/long the process is to upload a new version to maven is. After that there should be a version bump in the gradle of kegtab, and an update published to the play store, right?

**Comment by RePeet13** [comment]
@mik3y My poor kegerator is waiting to get its very own kegbot behind this issue, and updating the kegtab with the new library. Can you spare some time soon?

**Comment by RePeet13** [comment]
@mik3y any movement on this issue?

**Comment by RePeet13** [comment]
@mik3y Getting anywhere? It's been about a month.

**Comment by mik3y** [comment]
@RePeet13 sorry, I've had my hands full. But I have once again been re-united with my USB gear. I'll try to close this out this week.

**Comment by RePeet13** [comment]
👍

**Comment by RePeet13** [comment]
@mik3y ready to shipit?

**Comment by RePeet13** [comment]
@mik3y had a chance to package and upload yet?

**Comment by James-Firth** [comment]
Also wondering if the maven repo will be updated soon :)

Is the process cumbersome for you @mik3y or just haven't had a chance? If it's cumbersome I'm sure someone would be willing to help make it easier for you

**Comment by kai-morich** [comment]
now available on jitpack. see badge in README
