### ISSUE TITLE
Serial Buffer

### ISSUE THREAD

**Issue by mbt28** [mik3y/usb-serial-for-android#140]
Hi,

How should I collect streaming bytes to a buffer? In Java there are several methods but I am not sure which way is fits with my case more.

I would like to collect to data as an byte array then I will process them and finally I will remove the processed bytes. However I would like to have all the upcoming bytes to be added my array. Actually, Arduinos hardware serial like behavivour is exactly what I am looking for.

Which method should I use?

**Comment by mik3y** [comment]
Please use [the google group](https://github.com/mik3y/usb-serial-for-android#help--discussion) for help.
