### ISSUE TITLE
ControlTransfer with value 0x8 failed:-1

### ISSUE THREAD

**Issue by nsspw** [mik3y/usb-serial-for-android#145]
Excecute code:
usbSerialPort.open( connection );
show error :
"ControlTransfer with value 0x8 failed:-1"
Why?
(The vendorId and productId: 0x0d16, 0x0502)

**Comment by mik3y** [comment]
Closing troubleshooting issue. Consider the [the google group](https://github.com/mik3y/usb-serial-for-android#help--discussion) for further discussion.
