### ISSUE TITLE
GPL change? :)

### ISSUE THREAD

**Issue by magnusjjj** [mik3y/usb-serial-for-android#149]
Hi! One of the forks listed has changed its license to GPLV2, instead of GPLV3. Is this intentionally allowed? :)

https://github.com/DroidPlanner/usb-serial-for-android/commit/d1f189fc938f7871aaa30df2b8385cf47336b349

**Comment by greblus** [comment]
See here: 

https://github.com/mik3y/usb-serial-for-android/commit/c842a1d5f6a4ad6bd965ce43022690a800f18fea

Cheers,
W.

**Comment by mik3y** [comment]
As greblus notes, the project is & has been LGPL Version 2.1.
