### ISSUE TITLE
FindAllDriver returns empty driver list

### ISSUE THREAD

**Issue by goelankita** [mik3y/usb-serial-for-android#157]
Hello,

I am trying to connect to a hardware device which my organization build. I provided its VID and PID in xml files, but application is not able to detect my device. When I connect my device via USB, I got a messagebox asking that open this USB device by "SeialApp" and also USB device connected to phone. It means phone is detecting the device.

I tried to debug. "findAllDrivers" method is not returning any driver. I tried to connect a flash drive, my phone was able to open its file, but Serial USB application could not detect its driver too.

Please help. Any help will be appreciated.

Thanks so much in advance

**Comment by akshaytaru2007** [comment]
I am facing the same issue

**Comment by buyukyukselburak** [comment]
Could you solve this problem, if you success it, can you explain?

**Comment by akshaytaru2007** [comment]
Please do tell.

**Comment by 14331195** [comment]
+1

**Comment by 14331195** [comment]
I don't know how to solve this problem. Please help.

**Comment by hrshs** [comment]
I solve this problem by adding this
https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices

**Comment by josealonso** [comment]
> I solve this problem by adding this
> https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices

Me too, thanks for the suggestion.

**Comment by kai-morich** [comment]
use a custom prober as recomended in the 2 previous comments
