### ISSUE TITLE
UsbDeviceConnection.requestWait() never times out, so all reads are blocking on API 17+

### ISSUE THREAD

**Issue by micolous** [mik3y/usb-serial-for-android#159]
[Due to Android bug 39522](https://code.google.com/p/android/issues/detail?id=39522), it is not possible to use `UsbDeviceConnection.requestWait()` with a timeout.

At least the `CdcAcmSerialDriver` uses this on API Level 17+ to do a `read`.  This effectively makes all read operations blocking, even if the timeout is reached.

It would be useful to be able to explicitly specify `mEnableAsyncReads = false` to be able to always fall back to using `bulkTransfer`, which actually allows timeouts to be used.

**Comment by carl1990** [comment]
where the var mEnableAsyncReads I can found and set

**Comment by kai-morich** [comment]
0d48ed04e7cf3ff83c8089d4dedf61f1ba7277be always uses async read, as bulkTransfer can cause data loss. Blocking requestWait() are explicitely canceled on connection close. Blocking is not an issue, as reading should anyway be done in a separate thread.

**Comment by kai-morich** [comment]
nevertheless the functions should not block unexpectedly.
requestWait.requestWait() supports timeout since Android 8.0
on older Android versions should throw UnsupportedOperationException

**Comment by kai-morich** [comment]
read timeout is supported by all drivers with e2e9df846386ccdbf6625c057fd1cd5f94c16d41
