### ISSUE TITLE
Read/Write Data

### ISSUE THREAD

**Issue by dalwadi2** [mik3y/usb-serial-for-android#161]
I have NFC/RFID reader device which is connected via OTG, I am using this library to detect the device.
now I have to send some commands and read the relevant response from that device, I am new to hardware compatible app. 
can anyone suggest me how can I do that? 
please respond ASAP

**Comment by kai-morich** [comment]
this library only supports serial-to-usb converter chips. your NFC reader very likely uses a different protocol
