### ISSUE TITLE
Maven support for library

### ISSUE THREAD

**Issue by jubeira** [mik3y/usb-serial-for-android#163]
It would be very convenient to have the library available as a Maven package to incorporate it to projects directly without the need of building it from source.
I've seen #131 already takes into account uploading the next release; is there any update on this? The issue hasn't been closed by the date.

Thanks in advance.

**Comment by James-Firth** [comment]
I've added my 👍 to the issue, but I would also like to have a newer version available via Maven

**Comment by kai-morich** [comment]
now available on jitpack. see badge in README
