### ISSUE TITLE
How to communicate with more than one USB Serial devices

### ISSUE THREAD

**Issue by suyog44** [mik3y/usb-serial-for-android#164]
I am trying to make android code work which can communicate with multiple USB serial devices and android tablet.

I am able to communicate with single USB device at a time. but, now when I try to connect and communicate with multiple USB serial device App is failing.

**Comment by lukegluke** [comment]
Hi,
Use newCachedThreadPool as ExecutorService (to what SerialIoManager is submitted) instead of newSingleThreadExecutor.
