### ISSUE TITLE
Not working with FTDI311D IC

### ISSUE THREAD

**Issue by Omcsesz** [mik3y/usb-serial-for-android#171]
When I run it on my Android 6.0 phone, my FTDI311D devboard is not recognized.

**Comment by kfalasiri820** [comment]
Having the same issue, was wondering if this library is compatible with AOA chips/how one could get the FT311D chip to get recognized using this library.

**Comment by kai-morich** [comment]
this is chip is not supported by this library as it is not a serial-to-usb converter
