### ISSUE TITLE
how can i connect serial port with service from Broadcastreceiver

### ISSUE THREAD

**Issue by ctpxyza** [mik3y/usb-serial-for-android#172]
i need to close serial connection and reopen the connection from background, by after i receive usb state from broadcastreceiver, then use service to open connection, "can't connect" always shows to me. but if i start service from activity which register meta-data, it works will.
so , can you help me to let it works in the background. thx.

**Comment by HopeForWholeVillage** [comment]
i meet the same problem，it‘s must work whit activity，the connection will be null when i opendevice in Broadcastreceiver,i aslo regist the meta-data and the action

**Comment by ctpxyza** [comment]
> i meet the same problem，it‘s must work whit activity，the connection will be null when i opendevice in Broadcastreceiver,i aslo regist the meta-data and the action

i have found the reason of this issue, android usbhost in framework intercepts connection event and only pass the event to Activities which register the meta-data, then show a dialog to choose one of them.
