### ISSUE TITLE
Error with linking and compiling project

### ISSUE THREAD

**Issue by sujan-sube** [mik3y/usb-serial-for-android#177]
I get the following error message when I try to add usb-serial-for-android as a depenency for my project.

`Error: Project :library declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :libs:usb-serial-for-android:usbSerialForAndroid.`

Here is how my settings.gradle and build.gradle files look like:

**settings.gradle**
`include ':library', ':libs:usb-serial-for-android:usbSerialForAndroid'`

**build.gradle**
```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    testCompile 'junit:junit:4.12'
    compile project(':libs:usb-serial-for-android:usbSerialForAndroid')
}
```

**Comment by kai-morich** [comment]
instead of copying the source into your project you can now use a gradle library dependency, see https://github.com/mik3y/usb-serial-for-android#quick-start
