### ISSUE TITLE
Read USB Joystic input

### ISSUE THREAD

**Issue by gunnicus** [mik3y/usb-serial-for-android#179]
Hi I connected my usb logitech joystick to my android phone, I'm trying to get the joystick input using usb-serial-for-android. At the moment the app shows '0 devices found'. What should I do? Is there a driver for the joystick?

**Comment by olimaticer** [comment]
A joystick is a Human Input Device HID.
Use the activity event onKeyDown().

Maybe test it with a test version of RFO-Basic first.
The command is InKey$ key$, **keyEvent$**
[https://www.tapatalk.com/groups/rfobasic/hot-summer-of-code-t4408-s60.html#p35494](url)

**Comment by olimaticer** [comment]
Maybe I did not explain it good enough.
A joystick is a Human Input Device HID.
You do not need usb-serial-for Android!
Use the activity event, maybe  onKeyDown(), onKeUp() etc..

**Comment by kai-morich** [comment]
this library only supports serial-to-usb converts, not HID devices
