### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by gunnicus** [mik3y/usb-serial-for-android#180]
Hi, Is there a way to debug these code? I have only one usb mini port on my Android phone if I use that connect to a device then I can't connect the phone to PC. Is there a way to attach a usb device to android simulator?

**Comment by mockfrog** [comment]
On some versions of Android you have the option to connect adb via wlan. Have a look into the developer settings of your device. If that is not the case, and your device is rooted you could go the manual route, see https://www.droidwiki.org/wiki/Wireless_ADB for more info

**Comment by gunnicus** [comment]
Thank you sir, this worked.
