### ISSUE TITLE
Repo maintenance

### ISSUE THREAD

**Issue by jubeira** [mik3y/usb-serial-for-android#186]
PRs and issue count seem to keep growing over time, and it seems that there are plenty of users of this code around.

Has anyone been able to contact the owner/ maintainer? It would be awesome if this repo could be hosted by someone else with some time to maintain it and merge relevant contributions.

**Comment by pavi2410** [comment]
I agree with you. This library is indeed very useful and should be maintained to support more features.

**Comment by pavi2410** [comment]
How about if we fork this repo and maintain it, if @mik3y is not active anymore?

**Comment by mik3y** [comment]
Hey folks! I would definitely be happy to bring in some new maintainers, as pretty clearly I don't have the time (or the hardware gizmos) necessary to maintain things. Would be happy to see it live on with some better stewardship..

As there's some incomplete work in `master` & bunch of dangling issues, I'll try to spend some time on maintenance this weekend and see where we land.

(Of course, you should always feel free to fork!)

**Comment by Fyb3roptik** [comment]
Any update? I would love to have merged PR's please! I need to use this for a Mega. Will it work?

**Comment by pavi2410** [comment]
Can anyone help me in merging PRs if I create a fork? I will you as collaborator.

**Comment by mik3y** [comment]
Please see #191 !
