### ISSUE TITLE
 Router> prompt not showing after press RETURN to get started

### ISSUE THREAD

**Issue by chaitanyaInfinity** [mik3y/usb-serial-for-android#187]
Hello @mik3y ,

You made a fabulous library. It helping me a lot. Thank you very much.
I have one small issue. When we start up a router, after "press RETURN to get started" dialogue Router> prompt is not showing and after starting same from laptop it is visible in my application also.
Please help me for the same.
Thanks in advance

**Comment by kai-morich** [comment]
typically a wrong newline character issue
