### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#191]
Hi folks! I'm looking for someone to take over as maintainer for this project. As you can see, I haven't had the time to do so. (And I no longer have the devices to test, either!)

The new maintainer would have responsibility over reviewing submitted PRs, triaging issues, improving the code and publishing new releases. Ideally, you've already submitted PRs and/or maintain a fork, or have a track record from another open source project.

If you're interested, please leave a note below.

**Comment by kai-morich** [comment]
I can imagine taking over this project

**Comment by mik3y** [comment]
Hey @kai-morich - are you still interested in taking over? Let's give it a shot if so!

**Comment by kai-morich** [comment]
yes, please send mail for further steps

**Comment by eclectice** [comment]
I vote for kai ;)

**Comment by kai-morich** [comment]
you can reach at mail@kai-morich.de

**Comment by mik3y** [comment]
I've add you as a collaborator! If you'd like me to look at any pull requests, please poke me on them. Otherwise, feel free to merge as you see fit.

**Comment by kai-morich** [comment]
I will merge the stuff I collected over time and will have a look at the rest.

I assume this library has LGPL license because this licences is used by libFTDI.
But what is the reason for Google Copyright 2011-2012?
