### ISSUE TITLE
Request : Add support for CH340G

### ISSUE THREAD

**Issue by defvs** [mik3y/usb-serial-for-android#194]
The CH340G Usb-to-TTL device is included today in many Arduino clones out there. In fact it is cheap, works fine in most situation, but disadvantage is that software support is required (drivers for Windows for example)

By adding it, you will definitely support all Arduino out there, including unofficial ones.

If you want some clues, I think the app ArduinoDroid supports it.

**Comment by AliensInc** [comment]
Agree, will be very useful

**Comment by AliensInc** [comment]
Agree, will be very useful

**Comment by defvs** [comment]
Looks like there was some support but it doesn't seem to work well : see PRs #121 , and some more PRs are ready to merge like #195 #188 #156

**Comment by defvs** [comment]
Not working for me atleast

**Comment by kai-morich** [comment]
CH340G works for me with #121 included in master branch, the other PRs are extensions to support more options

**Comment by kai-morich** [comment]
PR #121 #195 #188 #156 are merged
