### ISSUE TITLE
CP2105 2 interfaces

### ISSUE THREAD

**Issue by iSTAYERi** [mik3y/usb-serial-for-android#198]
I have CP2105 with RS485 and RS232 interfaces, and if i get ports with code below - i get just 1 port.
`driver = availableDrivers[deviceNumber]`
`for ((i, port) in driver.ports.withIndex()) Toaster.print("\nPorts available: $i: $port")`

**Comment by kai-morich** [comment]
in the code you can see, that this port mechanism is not implemented at all. If you know the control commands to address the different ports, please try to enhance the code

**Comment by kai-morich** [comment]
multiport devices are supported with pull request #202

**Comment by iSTAYERi** [comment]
Thanks

**Comment by kai-morich** [comment]
#202 is merged
