### ISSUE TITLE
Returns null "manager.openDevice" with Prolific PL2303 

### ISSUE THREAD

**Issue by akdrmrk** [mik3y/usb-serial-for-android#200]
I can use ftdi driver successfully but the "openDevice" returns null everytime with Prolific PL2303.

What can be cause of this?

**Comment by kai-morich** [comment]
you get null if usbManager.requestPermission(..) is required. maybe you have done this for FTDI device some time ago, but now have to repeat that for the PL2303

**Comment by akdrmrk** [comment]
I used product id which return from driver.getDevice() but I noticed that, this is wrong product id. The proble is solved when adding all product id of prolific in device-filter

**Comment by kai-morich** [comment]
please close issue if resolved

**Comment by mehrhossin** [comment]
"The proble is solved when adding all product id of prolific in device-filter"
Can you tell me exactly what you added?
