### ISSUE TITLE
Alternative to the devious hack 

### ISSUE THREAD

**Issue by vyi** [mik3y/usb-serial-for-android#203]
[Here](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialExamples/src/main/java/src/com/hoho/android/usbserial/examples/SerialConsoleActivity.java) a `UsbSerialPort` object is passed via a static method, which is also termed "Devious" because it is a workaround. 
There it is said that a cleaner way would be to create the serialPort with arguments. 

Can you please give one example that shows this?

This looks tricky, the way demonstrated in the examples obtains first a driver from prober, then a port from the driver. Thus some example demonstrating the creation of usbPort from arguments would be a great help.

**Comment by kai-morich** [comment]
here https://github.com/kai-morich/SimpleUsbTerminal the object is serialized when passing to next fragment
