### ISSUE TITLE
How to connect to a serial port with this library

### ISSUE THREAD

**Issue by BrotherV** [mik3y/usb-serial-for-android#210]
Hi, I appreciate your work. Unfortunately I couldn't find a right way to connect to serial port, There are two different ways that you mentioned. first of them relate to jar library and second one relate to the last commit. In the first sample Jar file doesn't support any of control values such as stop bit and so on. Can you guide me to fix it? Even I can't connect to an Arduino.

Sample code:
UsbSerialProber prober = UsbSerialProber.getDefaultProber();
UsbSerialDriver driver = prober.probeDevice(device);
if(driver != null){
	List<UsbSerialPort> ports = driver.getPorts();
}

I have a device with vendor id 0x2341 but driver always return null.

Thanks in advance.

**Comment by kunofhan** [comment]
meet with the same problem

**Comment by kunofhan** [comment]
Thank for your share,wait online

**Comment by BrotherV** [comment]
Send an email an I'll reply it for you.  find my email in my profile.

**Comment by kunofhan** [comment]
haven't see your email in your profile

> Send an email an I'll reply it for you. find my email in my profile.

haven't see your email in your profile.

**Comment by kunofhan** [comment]
> haven't see your email in your profile
> 
> > Send an email an I'll reply it for you. find my email in my profile.
> 
> haven't see your email in your profile.



> Send an email an I'll reply it for you. find my email in my profile.

My email :956397053@qq.com , don't know whether you can send to me

**Comment by BrotherV** [comment]
> haven't see your email in your profile
> 
> > Send an email an I'll reply it for you. find my email in my profile.
> 
> haven't see your email in your profile.

I've sent you my codes. if you had any problem, you know how to find me.

**Comment by acaliaro** [comment]
@BrotherV could you share your work with me? Thanks

**Comment by eclectice** [comment]
You can refer https://github.com/mik3y/usb-serial-for-android/issues/220 for usage idea and a useful example app from kai-morich fork.

**Comment by acaliaro** [comment]
Thanks @eclectice I have found another solution

**Comment by BrotherV** [comment]
@acaliaro Sure, give me your email and I can send it all for you.

**Comment by acaliaro** [comment]
Thanks @BrotherV , I have found another good solution to this project. I will contact you if I will need your help in the future. Thanks again

**Comment by BrotherV** [comment]
@acaliaro Your welcome. feel free and contact me with this email: mohsen_hatami@ymail.com
Good luck

**Comment by kai-morich** [comment]
please look into examples at end of https://github.com/mik3y/usb-serial-for-android#quick-start for permission handling

**Comment by lythamhoa** [comment]
> I finally finished the project and I did it with two library(mik3y and felhr85 usb serial for android). If you would like, I can share what I did.

I need the for my project, Can you send me your code use mik3y or felhr85. Thanks. My email. thang.phamduc@gmail.com
