### ISSUE TITLE
driverClass = null匹配驱动为空

### ISSUE THREAD

**Issue by Michelle0716** [mik3y/usb-serial-for-android#211]
public Class<? extends UsbSerialDriver> findDriver(int vendorId, int productId) {
        final Pair<Integer, Integer> pair = Pair.create(vendorId, productId);
        return mProbeTable.get(pair);
    }

方法返回空

**Comment by eclectice** [comment]
The method is used in [UsbSerialProber.java](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/UsbSerialProber.java). Why do you get an empty result? Can you give the VID and PID you are trying to look for?

**Comment by kai-morich** [comment]
please check https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices
