### ISSUE TITLE
How I can get ch340 virtual com port interface?

### ISSUE THREAD

**Issue by WangLiang85** [mik3y/usb-serial-for-android#221]
I am debuggin ch340 driver in android (https://github.com/felHR85/UsbSerial). 
I need ch340 spec such as this document https://www.silabs.com/documents/public/application-notes/AN571.pdf 
But AN571.pdf is for cp2102.

How I can get this document for ch340?

**Comment by kai-morich** [comment]
http://wch-ic.com/product/CH340DS1_PDF.html
