### ISSUE TITLE
ch340: How I can baudrate with 74880?

### ISSUE THREAD

**Issue by WangLiang85** [mik3y/usb-serial-for-android#222]
On windows(tested with python  serial library), baudrate 74880 is working on ch340.

How I can implement in android?

How I can get the document of ch340?
I can get document of cp2102 (https://www.silabs.com/documents/public/application-notes/AN571.pdf).

**Comment by kai-morich** [comment]
please try https://github.com/kai-morich/usb-serial-for-android that supports more baud rates

**Comment by WangLiang85** [comment]
Thanks

**Comment by kai-morich** [comment]
solved with 73b8b73133c4fa2fc299824aa52082efc8bd6c32
