### ISSUE TITLE
manager.hasPermission(device) always returns null, even after giving permission through dialog( Android to VFD Pole Display)

### ISSUE THREAD

**Issue by iambaji** [mik3y/usb-serial-for-android#224]
I am trying to implement communication between pos android device(Clover which runs on android) and VFD display pole, the manager.openDevice(device) always returns null even after giving permission through dialog(Explicit) and implicit(manifest and intent filter, device_filter.xml)

Android: Clover Pos Device(USB port)
Pole Display Model: VFD01U

**Comment by kai-morich** [comment]
please look into examples at end of https://github.com/mik3y/usb-serial-for-android#quick-start for permission handling
