### ISSUE TITLE
Arduino Micro with productId 0037 is not recognized

### ISSUE THREAD

**Issue by tsirysndr** [mik3y/usb-serial-for-android#225]

**Comment by kai-morich** [comment]
according to https://github.com/arduino/ArduinoCore-avr/blob/master/boards.txt the PID 0037 is valid, but it's unusual. Typically VID=2341 + PID=8037 is used. You can add your IDs as shown here: https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices
