### ISSUE TITLE
How to distinguish the inserted usb port

### ISSUE THREAD

**Issue by zhangdongsheng123** [mik3y/usb-serial-for-android#234]
Hello, big brother, please consult, if multiple usb port, can distinguish which port is inserted

**Comment by kai-morich** [comment]
you could try using CommonUsbSerialPort.getSerial() to distinguish multiple devices, but I do not know if all devices really return useful serial numbers

**Comment by kai-morich** [comment]
see https://developer.android.com/reference/android/hardware/usb/UsbDevice.html#getDeviceName()

**Comment by zhangdongsheng123** [comment]
> 参见[https://developer.android.com/reference/android/hardware/usb/UsbDevice.html#getDeviceName（）](https://developer.android.com/reference/android/hardware/usb/UsbDevice.html#getDeviceName())

Thank god, I will try
