### ISSUE TITLE
Proguard configuration is missing

### ISSUE THREAD

**Issue by CrazyDude1994** [mik3y/usb-serial-for-android#237]
Hey! First of all, thank you for this library. I'm using this in my project which has been uploaded to Google Play. However I'm using ProGurd for release apk. And it seems like your library is using reflection and because of this a crash can be occured when calling 

```
val drivers = UsbSerialProber.getDefaultProber().findAllDrivers(usbManager)
```

It would be great if you could provide a proguard file for your project.

Thanks

**Comment by kai-morich** [comment]
please try 75f23e9a2de08a171f87469a5eda2e5332ffec2a

**Comment by CrazyDude1994** [comment]
Thanks, I'll try it today

**Comment by CrazyDude1994** [comment]
Seems good :+1:
