### ISSUE TITLE
Writing with CP2102

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#24]
_From [read.the...@gmail.com](https://code.google.com/u/106251791149112390104/) on May 10, 2013 13:55:16_

When I use UsbSerialDriver.write() or SerialInputOutputManager.writeAsync() it doesn't send nothing, instead it reads what I wrote.

Reading works fine, I write in Arduino serial monitor and I get it on Android, but as I said, nothing goes to Arduino from Android using write() or asyncWrite(), but when I read it returns me what I tryed to send. So weird.

_Original issue: http://code.google.com/p/usb-serial-for-android/issues/detail?id=24_

**Comment by kai-morich** [comment]
for arduino you have to set DTR+RTS
