### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by michaelonz** [mik3y/usb-serial-for-android#243]
I have an app that will run for about 10 minutes (the time fluctuates) and then the app freezes - the log reports that it is doing a lot of Garbage collections with over 46k objects.  I am using the CDC driver and it is sending a large amount of data (at 115k). 

in the link below 
[](https://stackoverflow.com/questions/46232314/trying-to-track-down-gref-leak)

it has been reported that the library was leaking but they didnt work out where - has anyone else had a similar issue?  Or is there any known issues?

NOTE: I am sending a lot of data so this may only occur under these circumstances.

**Comment by kai-morich** [comment]
there is no link in your issue

**Comment by kai-morich** [comment]
I am not aware of such leaks. please try ce97a3408bf37e5e7052be2283ebe2e747d6577f which significantly reduced number of UsbReqeuests
