### ISSUE TITLE
How to write data?Have you demo?

### ISSUE THREAD

**Issue by puwenjie** [mik3y/usb-serial-for-android#247]
How to write data? Like “ int numBytesRead = port.read(buffer, 1000);”
I use “port.write(data,10)”, and find "if(mConnection == null) {
                 Throw new IOException("Connection closed");
             }"

**Comment by kai-morich** [comment]
please look at https://github.com/mik3y/usb-serial-for-android#quick-start. at the end of that section some more complex examples are mentioned
