### ISSUE TITLE
have you a simple example for writiing ?

### ISSUE THREAD

**Issue by puwenjie** [mik3y/usb-serial-for-android#248]
Cannot write data on the bus.
Write the data, but can't read it on the bus.

**Comment by puwenjie** [comment]
I can see the data I sent on the sent interface, but I can't see it on the bus, indicating that the written function can't send data to the bus. This means sending failed.

**Comment by kai-morich** [comment]
please try https://github.com/kai-morich/SimpleUsbTerminal

**Comment by puwenjie** [comment]
I tested this demo, but I can't write data on the bus.
Is it a demo to add headers to the message？ I guess

**Comment by kai-morich** [comment]
SimpleUsbTerminal does real read + write, but is limited in setting baud rate, newline mode and other serial propertes, so you probably have to adapt it to match your device
