### ISSUE TITLE
can't read data from FTDI FT232

### ISSUE THREAD

**Issue by mingxin-yang** [mik3y/usb-serial-for-android#249]
I use the example, I can get the serial device name is FtdiSerialPort, but I can't get CD, CTS, DSR...., all of them return disabled, **SerialInputOutputManager.Listener** can't return some data too

**Comment by kai-morich** [comment]
please try latest commit, where FTDI control lines were added

**Comment by mingxin-yang** [comment]
@kai-morich I had tried this, It can't work, I have a problem that it is isn't  the phone need root?

**Comment by kai-morich** [comment]
this library does not need root.

**Comment by mingxin-yang** [comment]
Thanks, I had read data successfully, Is there a third-party library for the modbus protocol?
