### ISSUE TITLE
SimpleUsbTerminal can not write data!?

### ISSUE THREAD

**Issue by puwenjie** [mik3y/usb-serial-for-android#250]
https://github.com/kai-morich/SimpleUsbTermina
I tested this demo, but I can't write data on the bus.
Is it a demo to add headers to the message？ I guess

**Comment by kai-morich** [comment]
SimpleUsbTerminal does real read + write, but is limited in setting baud rate, newline mode and other serial propertes, so you probably have to adapt it to match your device

**Comment by kai-morich** [comment]
duplicate to #248
