### ISSUE TITLE
Generating jar file

### ISSUE THREAD

**Issue by FredGr** [mik3y/usb-serial-for-android#255]
I would like to generate the jar file of usb-serial-for-android to use in a Cordova plugin. However the createFullJarRelease gradle task does not exist any longer. 
How can I produce the jar ?

Regards.

**Comment by kai-morich** [comment]
in Android Studio the `createFullJarRelease` task is shown in Gradle window `usbSerialForAndroid->Tasks->other` folder

**Comment by FredGr** [comment]
Thanks a lot for the answer but I am not very familiar with android.
How can i import the project into Android Studio and reach the Gradle Window ?
