### ISSUE TITLE
Link to device_filter.xml on the main page is not working anymore

### ISSUE THREAD

**Issue by thirstyone** [mik3y/usb-serial-for-android#257]
2. Copy device_filter.xml to your project's res/xml/ directory.

**Comment by kai-morich** [comment]
when I click on the link, the xml file content is shown. Please describe issue in detail

**Comment by thirstyone** [comment]
oops! wrong repository (got lost in my two tabs between two browsers). please, disregard this issue report - it was intended for this project: 
https://github.com/eric2036/usb-serial-for-android
however, will your implementation support the stm32 usb-serial driver? do I need to add anything to device_filter.xml? (haven't tried it yet - building an stm device)

**Comment by kai-morich** [comment]
STM devices use the CDC-ACM driver. There should be no need to modify the library. 

If your device uses VID/PID not known to the library, you should add a custom prober and if you want autostart you can also add the IDs to the xml copied into your app
