### ISSUE TITLE
Error opening device: init failed: #2

### ISSUE THREAD

**Issue by gokhanplt** [mik3y/usb-serial-for-android#258]
![image](https://user-images.githubusercontent.com/23299481/73647815-57777100-468d-11ea-8403-0179d629824d.png)

![image](https://user-images.githubusercontent.com/23299481/73647319-48dc8a00-468c-11ea-91a9-29d05451438c.png)

![image](https://user-images.githubusercontent.com/23299481/73647505-ac66b780-468c-11ea-8795-2a41f3ba9e59.png)

I want to connect one scale, but it gives such an error. Could you help?

**Comment by kai-morich** [comment]
please try latest version with fix for ch340 initialization

**Comment by gokhanplt** [comment]
> please try latest version with fix for ch340 initialization

![image](https://user-images.githubusercontent.com/23299481/73821535-3174dc80-4805-11ea-88d9-d365f0371660.png)
The connection was successful. But it returns such a value.
It returns normal value in Windows.

**Comment by kai-morich** [comment]
you very likely have to adapt the baud rate or other serial settings in the sample app

**Comment by kai-morich** [comment]
fix included in v2.2.1
