### ISSUE TITLE
Question: How to use device with generic usbserial-driver

### ISSUE THREAD

**Issue by OE4AMW** [mik3y/usb-serial-for-android#259]
I have a device (a radio with USB-interface), that is not recognized by linux, but works it works using the generic usbserial-driver, when called with the VID/PID during loading of the driver:
( using "insmod usbserial vendor=0x#### product=0x####" as described in https://www.kernel.org/doc/html/latest/usb/usb-serial.html ).
At the moment, I am using java with librxtx to interface the device. Now I am thinking about porting my application to android. Will/might any of the drivers provided by usb-serial-for-android work?

**Comment by kai-morich** [comment]
if your device uses one of the supported chips, it should work with a [custom prober](https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices) using the appropriate driver class
