### ISSUE TITLE
crass on iary data

### ISSUE THREAD

**Issue by 8th-bit** [mik3y/usb-serial-for-android#261]
Hi,

I am using this lib to communicate with arduino nano. If nano sends string data with serial.print and it all works fine. If I use serial.write with nano to transmit binary data, it works well as long as any transmitted bytes does not have highest bit set. If highest bit (0x80) is set, library stops runing as run function is stoped by something. Both systems are using same settings, that is 8-bit data, one stop bit, no parity. 

Has anyone seen anything like this, what might be the problem? 

br Mikko

**Comment by kai-morich** [comment]
Please provide more info. Without info one can only guess. Could be a conversion issue from signed Java byte to unsigned integer with wrong handling for negative byte with highest bit set.

**Comment by 8th-bit** [comment]
Thanks for your comment, I think I found the issue. Nothing to do with your lib, it was display lib I am using that did not support 8th bit.
