### ISSUE TITLE
support sending of BREAK signal

### ISSUE THREAD

**Issue by kai-morich** [mik3y/usb-serial-for-android#269]
some devices require a BREAK signal to enter a special diagnosis mode.

As workaround you can send a zero byte with low baud rate

**Comment by sarasini** [comment]
I need BREAK signal too.

thanks

**Comment by elmscansoft** [comment]
I am also need BREAK signal.

**Comment by kai-morich** [comment]
implemented with 768f7166001e62261915285ed3923f0609477b0e
