### ISSUE TITLE
bad practice for unimplemented features

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#27]
_From [alibabas...@web.de](https://code.google.com/u/102119318426848537300/) on May 17, 2013 02:21:22_

In class CdcAcmSerialDriver (and probably others) there are unimplemented methods. That's ok, but they return static values. Instead they should throw a java.lang.UnsupportedOperationException. This is to keep people from depending on these static values that might change in the future and break their implementations.

_Original issue: http://code.google.com/p/usb-serial-for-android/issues/detail?id=27_

**Comment by kai-morich** [comment]
with https://github.com/mik3y/usb-serial-for-android/commit/7423fd9d79b330544743477b235e7d424f7ceb97 a diferent solution is implemented to identify unimplemented features
