### ISSUE TITLE
connection to cdc failed :android permission denied

### ISSUE THREAD

**Issue by jins6611** [mik3y/usb-serial-for-android#270]
I am getting this error when i have a serial and video interface. I am unable to connect

**Comment by kai-morich** [comment]
probably your USB permission handling is missing. Please have a look at permission handling in https://github.com/kai-morich/SimpleUsbTerminal/blob/master/app/src/main/java/de/kai_morich/simple_usb_terminal/TerminalFragment.java

**Comment by jins6611** [comment]
This issue is occurring for the same app in playstore too.

**Comment by jins6611** [comment]
Issue is fixed i changed the target sdk to 27 and removed android.hardware.usb.host feature from manifest

**Comment by kai-morich** [comment]
looks like android.hardware.usb.host is not really required, so I will try to remove from the example app.

https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal does not use android.hardware.usb.host in manifest, has target sdk 28 and minsdk 18, so looks very similar to your solution. Do you have any idea, why your change solved the issue.

**Comment by jins6611** [comment]
> looks like android.hardware.usb.host is not really required, so I will try to remove from the example app.
> 
> https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal does not use android.hardware.usb.host in manifest, has target sdk 28 and minsdk 18, so looks very similar to your solution. Do you have any idea, why your change solved the issue.

 I think video and CDC interface both will try to use the usb host hardware feature if the mobile device support this
