### ISSUE TITLE
Direct Read and Write not Working

### ISSUE THREAD

**Issue by JairajJangleSLIOT** [mik3y/usb-serial-for-android#271]
For direct Read:
I am getting empty byteArray when I do `serialPort.read(data, timeout)` on button click but the read data listener is giving correct data. On the other end, I am using Arduino which is continuously sending data to the Android device. I want to capture what the Arduino is sending at that instance on button click and do not want to implement USB on data listener. 

For direct Write:
I am getting the same error `java.io.IOException: Error writing 6 bytes at offset 0 length=6` when I try to `serialPort.write(msg, timeOut)` on my USB device which is Arduino which is directly connected via USB so no question of improper connection. After `serialPort.open(connection)` here is what I have done with setParameter:

```
serialPort.setParameters(
    BAUD_RATE, /* 9600 */
    8,
    UsbSerialPort.STOPBITS_1,
    UsbSerialPort.PARITY_NONE
)
serialPort.dtr = true
serialPort.rts = true
```

I do not understand what changing endpoint means. If someone can give a clear explanation fo what exactly to do to solve the issue, it would be great.

**Comment by kai-morich** [comment]
this write error can have different reasons. typical are timeout too short, connection already closed

**Comment by JairajJangleSLIOT** [comment]
If I do not use SerialInputOutputManager then I get this error while writing: `java.io.IOException: Error writing 6 bytes at offset 0 length=6 Android USB`. And direct read is not working even when I do that. 
I am not able to find any example app for direct R/W or am I missing something.

**Comment by kai-morich** [comment]
[this](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/androidTest/java/com/hoho/android/usbserial/DeviceTest.java#L1329) test uses direct read and basically all of the tests use direct write

**Comment by JairajJangleSLIOT** [comment]
Thanks for the solution, I will test this out and post the updates.

**Comment by juCortez** [comment]
Hi, my name is Juliano. I am facing exactly same problem. Did you found a way to read data??

**Comment by JairajJangleSLIOT** [comment]
@juCortez No, for direct reading I tried removing SerialInputOutputManager, which is causing a write error: `java.io.IOException: Error writing 6 bytes at offset 0 length=6 Android USB` where 6 is the number of bytes I am writing in one go; direct `serial.read(...)` is still not working. I have checked the test cases @kai-morich suggested to look at, I am still working on understanding it, will post updates here if I find anything new.

**Comment by juCortez** [comment]
ok, thanks for reply!
best regards,

Em qua., 8 de abr. de 2020 às 01:57, JairajJangleSLIOT <
notifications@github.com> escreveu:

**Comment by kai-morich** [comment]
please have a look at the latest example app, it supports event-based and direct read

**Comment by JairajJangleSLIOT** [comment]
@kai-morich Thanks for updating the example app, direct Read works!!

**Comment by BhaurajBiradar001** [comment]
@JairajJangleSLIOT - What code you changed to work read directly?
