### ISSUE TITLE
Permission code in quickstart

### ISSUE THREAD

**Issue by filipeisho** [mik3y/usb-serial-for-android#274]
Hi, 
if I define my devices_filter.xml file, do I need to handle permissions? On the other hand if I was trying to get all the connected devices should I ask for permission first? Sorry for the questions... I am an android noob. I saw that there was some permission handling in the quickstart code, is that the code I am missing to be able to read any device? 
`        // add UsbManager.requestPermission(driver.getDevice(), ..) handling here`

Thanks!

**Comment by kai-morich** [comment]
you always need permission handling. See example app for details.
The device_filter.xml is only used to get your app automatically started, when an USB device is attached
