### ISSUE TITLE
onNewData receive bytes may loss highest bit

### ISSUE THREAD

**Issue by butyesbutno** [mik3y/usb-serial-for-android#277]
Hi, thanks for you tools. 
I use CH34x chip for usb serial convert
I send three bytes " 0x03 0x82 0x87  " over serial tool, onNewData callback sometime  got data correctly, sometime got "0x03 0x02 0x07".
change to another serial tool, the problem exists.
I am not sure of it is a bug..

**Comment by kai-morich** [comment]
looks like the baud rate of your serial device is slightly to high/low causing the last bit to be lost sometimes. please try with custom baud rate

**Comment by butyesbutno** [comment]
thanks for you advice.
changed the serial lines, then all goes well!
