### ISSUE TITLE
Is a Start Bit possible

### ISSUE THREAD

**Issue by lawtonykaps** [mik3y/usb-serial-for-android#278]
Hi, great software. I am involved in writing software which also requires a start bit. Is this easy to implement?  If so, please guide me to where I could make this change myself.

Many thanks in advance.

**Comment by kai-morich** [comment]
serial communication (rs-232) always has a start bit, so there shouldn't be anything todo

**Comment by lawtonykaps** [comment]
The question was unresearched. Everything else is set correctly, baud rate, stop bits etc. The only left to play with is the wait time.

**Comment by kai-morich** [comment]
is your question still open?
