### ISSUE TITLE
Ayuda para usar en MIT app inventor

### ISSUE THREAD

**Issue by horaciocastro7** [mik3y/usb-serial-for-android#280]

**Comment by kai-morich** [comment]
I am not an expert on MIT app inventor.
If you need a `jar` file for app inventor, please follow [instructions](https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#does-this-library-work-with-ioniccordovaxamarinapp-inventor-development-framework)
If you find more information, please share, so I can update the wiki
