### ISSUE TITLE
IOException: Expected 0xff bytes, but get 0xf0

### ISSUE THREAD

**Issue by yfengtech** [mik3y/usb-serial-for-android#282]
To fix this problem, I looked at the source

in the tag 2.2.2, class `Ch34xSerialDriver`, line 184 is
`checkState("init #6", 0x95, 0x0706, new int[]{0xff, 0xee});`

but I cloned the project, I found something wrong with line 184,
`checkState("init #6", 0x95, 0x0706, new int[]{-1, 0xee});`

I think that's the problem, but why?

**Comment by kai-morich** [comment]
this change is already included in https://github.com/mik3y/usb-serial-for-android/commit/5096d6940cf6d8fbe283864eaceb98dea128ec6d
I didn't create a new release yet, as I wanted to check if the second byte also has to be relaxed, but my Ch340 order got stuck due to corona
