### ISSUE TITLE
  sendAcmControlMessage() negative result?

### ISSUE THREAD

**Issue by 4ntoine** [mik3y/usb-serial-for-android#284]
Hey, I can see in the [source code](https://github.com/mik3y/usb-serial-for-android/blob/33149b66fd4fbfb313cb5d88ec1936936a543049/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java#L300) `sendAcmControlMessage()` (to be correct it's `mConnection.controlTransfer()` result) in case of negative value an exception is thrown.

It happens in my app on some devices (and i can't reproduce it as i don't have them) and i have no ideas on how it can be fixed. Any ideas why it happens or how to fix it?

**Comment by kai-morich** [comment]
I haven't seen such issues with my CDC devices. Maybe you use some unsupported baud rate or other values?

Regarding your previous comment on the return value:
so far all methods using sendAcmControlMessage are only sending data so there is no relevant result length in the return value. If there would be methods reading data, they would have to check the return value.

**Comment by 4ntoine** [comment]
@kai-morich Thanks for replying.

Nope, exactly the same code works (no baud rate there (just `mConnection.controlTransfer(0x21, 0x22, 0x00, mInterfaceNum /* actually 0 */, null, 0, 0);`)) in different ways returning negative values on some devices.
I can'y see any correlation with manufacturer, device, Android OS version but i have the logs (Firebase Crashlytics with events and logs and stacktrace)

**Comment by kai-morich** [comment]
closed as not reproducible
