### ISSUE TITLE
Does this library support simultaneous opening and operation of multiple CH340

### ISSUE THREAD

**Issue by howtoplay** [mik3y/usb-serial-for-android#287]
Does this library support simultaneous opening and operation of multiple CH340

**Comment by kai-morich** [comment]
yes, thats possible, just use all items returned by `UsbSerialProber.getDefaultProber().findAllDrivers`

the biggest chalenge is distinguishing the devices. To my [analysis](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/androidTest/java/com/hoho/android/usbserial/DeviceTest.java#L1700)  CH340 does not provide serial numbers. The device ID and position in the list depends on the order the devices where attached, not the USB bus topology.
