### ISSUE TITLE
CP2102 USB packet loss during read

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#29]
_From [felix.ha...@gmail.com](https://code.google.com/u/105183962478432605441/) on May 26, 2013 06:06:12_

When reading larger amounts of data using cp2102, in my case flight records download from a GPS flight recorder with 19200 baud, there are often missing data segements. The missing segments are always 64 bytes large, which is the read endpoint's max packet size. So it seems that sometimes a USB packet is missing.

Tested with a Nexus 7 tablet.

_Original issue: http://code.google.com/p/usb-serial-for-android/issues/detail?id=29_

**Comment by abhishekkumar1902** [comment]
Is this issue fixed yet? 
I am using the latest library and running my USB connection on 9600 baud rate, I am getting frequent packet loss like one or two in a packet of 100 bytes of data.
 
You also mentioned about replacing bulktransfer() with UsbRequests API, can you please tell me how to use that?

Please help!

**Comment by DRSDavidSoft** [comment]
As a sidenote, the author of [Serial USB Terminal](https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal&hl=en) uses the same `usb-serial-for-android` library, but apparantly got it right.

Compiled app from the `/usbSerialExamples` directory will reproduce the same reading packet loss, while the mentioned app works flawlessly. A quick decompilation of that app confirms that it is indeed using `usb-serial-for-android`.

**Comment by kai-morich** [comment]
you should use latest version that has UsbRequests API instead of bulkTransfer
