### ISSUE TITLE
port.close() close also UsbDeviceConnection()

### ISSUE THREAD

**Issue by AsladaGSX** [mik3y/usb-serial-for-android#292]
My device has CDC DAT, COMM and CCID interface.
CommonUsbSerialPort.close() method call CommonUsbSerialPort.closeInt() method and UsbDeviceConnection.close().
CommonUsbSerialPort.closeInt() closes interfaces only, this is OK.
but calling UsbDeviceConnection.close() disconnect also CCID interface using by my application, this cause a problem in my application.

I think closing UsbDeviceConnection is my application's responsibility.

**Comment by kai-morich** [comment]
you're right. The short example in [README](https://github.com/mik3y/usb-serial-for-android/blob/master/README.md) also shows that the deviceConnection is opened before and is just handed over to `UsbSerialPort.open()`, so it would make sense to close it separately after `UsbSerialPort.close()`.

But this would be an incompatible change, and it's also more convenient for the usual case to close the connection.

Instead I could think of an additional method `close(boolean closeUsbDeviceConnection)` or you pass in a derived `UsbDeviceConnection` object, where the `close()` method simply does nothing

**Comment by kai-morich** [comment]
please try with individual `usbManager.openDevice(...)` for each interface. 
In my tests, it worked with individual `UsbDeviceConnection` for each port of a multi-port serial device and failed after first close if the connection was shared.

**Comment by AsladaGSX** [comment]
It works. Thanks many!

**Comment by kai-morich** [comment]
updated javadoc comment with https://github.com/mik3y/usb-serial-for-android/commit/963729924b9fa70baf68da00ba384f8985f292eb
