### ISSUE TITLE
Setting serial port buffer size and some additional question

### ISSUE THREAD

**Issue by mucolores** [mik3y/usb-serial-for-android#293]
First of all, Sorry for bothering developers,
I've got some problem while developing android applications while using the library.
1. I'm wondering is there any way to set or get the buffer size of the serial port object, or did I have any way to implement the need.
2. Will I be able to know what is the queueing discipline for the buffer in the serial port object.
    If yes, do anyone who know how to get the information?
    If no, is there any way to implement the queueing discipline for serial port?

**Comment by kai-morich** [comment]
The library does not do any buffering, e.g. `write` will immediately do an USB request.

But the USB devices do buffering:
* https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#when-reading-a-message-why-dont-all-bytes-arrive-at-the-same-time
* https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#is-write-synchronous
