### ISSUE TITLE
cannot resolve symbol 'BuildConfig'

### ISSUE THREAD

**Issue by vijay180396** [mik3y/usb-serial-for-android#294]
i have downloaded the usb-serial-for-android(master) branch.And i import in android studio 4.0.1 .
it shows an error in **terminalfragment.java** at line of 47 **buildconfig** it not resolved.

**Comment by vijay180396** [comment]
now i find out why i get this error.
Due to i not added dependencies of com.github.mik3y:usb-serial-for-android:2.3.0 in build.gradle(usbSerialExample).
but i cannot able to find **APPLICATION_ID ** in BuildConfig

**Comment by kai-morich** [comment]
BuildConfig is generated when you build the project

**Comment by vijay180396** [comment]
![errorbuild](https://user-images.githubusercontent.com/54543391/88024198-f61a6000-cb4f-11ea-80d3-7910efe1d070.jpg)

**Comment by vijay180396** [comment]
and also it's doesn't assign any APPLICATIONID in **BuildConfig.class**
![missing](https://user-images.githubusercontent.com/54543391/88030307-b310ba80-cb58-11ea-83c7-5125194be5b6.jpg)

**Comment by kai-morich** [comment]
APPLICATION_ID is only set in BuildConfig of the example app, not BuildConfig of the library, but you can also replace the variable with the actual value in your fork

![grafik](https://user-images.githubusercontent.com/25850372/88051113-6331f380-cb58-11ea-9df6-2081ae519ac0.png)

**Comment by vijay180396** [comment]
thank you sir!, now the build get works

**Comment by Jagdish-958** [comment]
not generated BuildConfig in java(generated)
