### ISSUE TITLE
Some question about library using

### ISSUE THREAD

**Issue by mucolores** [mik3y/usb-serial-for-android#301]
First of all, Sorry for bothering developers,
I've got some question with the library.

I'm wondering can this library using on pure java project.
I'm developing another project on Raspberry Pi, but there're some problem for C library in Raspberry.
then I tried the same device on android system and it works, so I'm wonder is it possible using this library to build a java project in my Raspberry project?

mucolores,

**Comment by kai-morich** [comment]
This library is only for Android as it is build on top of Android specific USB api
