### ISSUE TITLE
What is the difference between this library vs https://github.com/felHR85/UsbSerial

### ISSUE THREAD

**Issue by MarsPlanet** [mik3y/usb-serial-for-android#304]

**Comment by kai-morich** [comment]
Basic functionality is similar.  
This library has slightly less exotic features (e.g. currently no flow control or break signal) but more feature completeness over different devices.  
When I started choosing a library, this one looked cleaner and more consistent to me, but that might be a matter of taste.

**Comment by Steakache** [comment]
First thing I can see ... the implementation 'com.github.felHR85:UsbSerial:6.1.0' works comparatively to this repo 'com.github.mik3y:usb-serial-for-android:Tag' ...
