### ISSUE TITLE
[Hint] in which part of code implementing "Fixed length messages" reading?

### ISSUE THREAD

**Issue by RacingMat** [mik3y/usb-serial-for-android#307]
First of all, a massive congratulation for your work and your sharing! 🥇 @mik3y 

I nearly succeeded in customizing your example with my Arduino MEGA :-) but I'm experimenting what you're describing there:
my message (10 bytes long) is truncated in several parts when I call private void receive(byte[] data) in Terminalfragment.java
https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time

Could you please hint me which file and which function of the code I should modify to implement "Fixed length messages" or "Newline-terminated messages"?
Thanks!
Inside usbSerialPort.read to wait until the length is fine? or concat byte arrays of truncated message from read?

`    private void read() {
        if(!connected) {
            Toast.makeText(getActivity(), "not connected", Toast.LENGTH_SHORT).show();
            return;
        }
        try {
            byte[] buffer = new byte[8192];
            int len = usbSerialPort.read(buffer, READ_WAIT_MILLIS);
            receive(Arrays.copyOf(buffer, len));
        } catch (IOException e) {
            status("connection lost: " + e.getMessage());
            disconnect();
        }
    }`

**Comment by kai-morich** [comment]
you should add a loop aroung your `usbSerialPort.read` to loop until you recieved enough data or time out
