### ISSUE TITLE
Flow Control

### ISSUE THREAD

**Issue by xmutzlq** [mik3y/usb-serial-for-android#309]
usb-serial-for-android can set "Flow Control"?

**Comment by kai-morich** [comment]
no, flow control is not supported

**Comment by kai-morich** [comment]
but you can set/unset flow control lines. that is sufficient for uses cases like resetting arduino with DTR

**Comment by kai-morich** [comment]
describe control flow support in [wiki](https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#Feature_Matrix)
