### ISSUE TITLE
how to support cp2104

### ISSUE THREAD

**Issue by xchengDroid** [mik3y/usb-serial-for-android#310]

**Comment by kai-morich** [comment]
have you already tried to use it with this library?

**Comment by xchengDroid** [comment]
sorry i did not try to use it, but I see the source of Cp21xxSerialDriver.java only support 2102,2105,2108,2110.

**Comment by kai-morich** [comment]
it's not tested against cp2104 therefore it is not mentioned. please try

**Comment by xchengDroid** [comment]
> 它没有针对cp2104进行过测试，因此未提及。请尝试
thank you ,it works well in cp2104!

**Comment by kai-morich** [comment]
readme updated with f35aa44cddf2f18221ca22d9ee07e6065fcb5f4c
