### ISSUE TITLE
Can i directly communicate using serial converter cables (ftdi)  or will i need adruino chips as middleware ? 

### ISSUE THREAD

**Issue by gamenic-babin** [mik3y/usb-serial-for-android#316]

**Comment by kai-morich** [comment]
depends on your use case. typically a serial converter cable is sufficient.

**Comment by gamenic-babin** [comment]
Thank you sir for quick reply i will try once i get my hands on the device .

**Comment by kai-morich** [comment]
closed due to inactivity
