### ISSUE TITLE
Can you read more than 1024 bytes of information?

### ISSUE THREAD

**Issue by AlvaroPulidoBernal** [mik3y/usb-serial-for-android#319]
Hi, Thank you for your code.

I use direct read from a serial port 
port.read(response, READ_WAIT_MILLIS);
when i send small bytes arrays i read them just fine but when i send a byte array of size greater than 900 bytes i only get 575 bytes or less readed from the port
is it wrong? or i need to do something else

**Comment by kai-morich** [comment]
please see https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time

**Comment by AlvaroPulidoBernal** [comment]
Thanks for the reply, I'll see it and follow the recommendations taht mentions

**Comment by kai-morich** [comment]
closed due to inactivity
