### ISSUE TITLE
Support for ARK3116 device

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#32]
_From [tasanak...@gmail.com](https://code.google.com/u/108765877364410034156/) on July 07, 2013 21:53:35_

Reference Linux Driver 
    drivers/usb/serial/ark3116.c

_Original issue: http://code.google.com/p/usb-serial-for-android/issues/detail?id=32_

**Comment by kai-morich** [comment]
this is a very rarely used devices. It's unlikely to be added here
