### ISSUE TITLE
Question: Will this work with CY7C65213 chip?

### ISSUE THREAD

**Issue by RandunuK** [mik3y/usb-serial-for-android#321]
Hi, 

`<usb-device vendor-id="1204" product-id="3" /> <!-- 0x04B4: CY7C6...>`

Will this library work with CY7C65213 chip only doing the above change to the **device_list.xml**

(Currently I haven't this chip. So cannot test it myself. )

Thank you

**Comment by kai-morich** [comment]
the CY7C6521x chip family is not supported

**Comment by RandunuK** [comment]
Thank you @kai-morich

**Comment by kai-morich** [comment]
I am not an expert on CY7C6521x. Maybe it needs a dedicated driver, but maybe it works with existing CDC driver. I only found something about a proprietary libsb wrapper and CDC compatibility for differently numbered CY7C... device. You would have to try or investigate yourself.
If it works with CDC driver, you should add the VID/PID mapping to a custom prober class and additionally you can use the device_list.xml for autostart of your App.

**Comment by RandunuK** [comment]
Thank you @kai-morich .
