### ISSUE TITLE
[question] Find consultations about lib and ide

### ISSUE THREAD

**Issue by whoim2** [mik3y/usb-serial-for-android#323]
Hello! I want to write a simple open source application using this library for the RC community, have different programming experience, but not for Android. These are essentially simple operations of reading / parsing responses and sending new values, a configurator for a free radio device called QLRS.
Can anyone help me with advice from the very beginning, which IDE to install and so on? There will probably be a lot of questions, telegram chat is supposed.
I will be grateful.

**Comment by kai-morich** [comment]
a lot of information on Android development is provided here: https://developer.android.com/
