### ISSUE TITLE
Error writing

### ISSUE THREAD

**Issue by xmutzlq** [mik3y/usb-serial-for-android#324]
why Error writing 2760 bytes at offset 0 length=2760 when I send base64 data?

**Comment by kai-morich** [comment]
please verify that your timeout is long enough to send all data. for details see the [wiki](https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#How_to_set_timeout_in_codereadcodecodewritecode_methods)

**Comment by kai-morich** [comment]
closed due to inactivity and insufficient error context information
