### ISSUE TITLE
CH340K无法使用，win测试是正常的

### ISSUE THREAD

**Issue by adsl865** [mik3y/usb-serial-for-android#335]
CH340C 可以使用  CH340k无法使用  不知道是什么原因 
在WIN 测试都是正常的

**Comment by kai-morich** [comment]
Your issue is not clear from google translate. Please rephrase or write in english.

**Comment by adsl865** [comment]
CH340C can be used, but CH340k cannot be used. I don’t know why.

**Comment by kai-morich** [comment]
What is the issue? Is the device not detected at all, does connection fail or transfer fail? Have you checked this device at a Windows or Linux computer?

**Comment by adsl865** [comment]
The WIN test is normal, the Raspberry Pi is also normal, and the Android test fails.

**Comment by adsl865** [comment]
CH340C can be used on Android, but CH340k K suffix cannot be used.

**Comment by kai-morich** [comment]
Is the device not detected at all, does connection fail or transfer fail?

**Comment by adsl865** [comment]
Is the device not detected at all

**Comment by kai-morich** [comment]
is the device shown with an app that lists all USB devices (e.g. [USB device info](https://play.google.com/store/apps/details?id=aws.apps.usbDeviceEnumerator))?
