### ISSUE TITLE
USB Serial android library supports flashing?

### ISSUE THREAD

**Issue by jesuelab** [mik3y/usb-serial-for-android#337]
I am using ATmega2560 (CH340) Microcontroller boards .Is it possible to flash by using hex file in android by using usb serial library.  I am using physicaloid library , but it does not support Ch340 . Is there any alternate libarry for flashing in android.

**Comment by jesuelab** [comment]
> I am using ATmega2560 (CH340) Microcontroller boards .Is it possible to flash by using hex file in android by using usb serial library. I am using physicaloid library , but it does not support Ch340 . Is there any alternate libarry for flashing in android.

**Comment by jesuelab** [comment]
I am using ATmega2560 (CH340) Microcontroller boards .Is it possible to flash by using hex file in android by using usb serial library. I am using physicaloid library , but it does not support Ch340 . Is there any alternate libarry for flashing in android.

**Comment by kai-morich** [comment]
the library only provides low level serial communication. You can build a flashing library/app on top

**Comment by jesuelab** [comment]
any suggestion kai ??

**Comment by kai-morich** [comment]
I did not use flashing from Android, so I cannot recommend an App or Library
