### ISSUE TITLE
使用USB Hub,如何同时与两个USB设备通讯?How to use USBhub to connect two devices at the same time?

### ISSUE THREAD

**Issue by AlexFugui** [mik3y/usb-serial-for-android#338]
使用USB Hub连接了两个通讯主机,如何保证同时收到数据呢?(分别是两个读卡器)
Using USB hub to connect two communication hosts, how to ensure to receive data at the same time? (two card readers respectively)?
thanks!

**Comment by kai-morich** [comment]
see [wiki](https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#Can_I_open_multiple_connections_in_one_application)
