### ISSUE TITLE
Is Android 8.1 compatible with this source?

### ISSUE THREAD

**Issue by CJH7396** [mik3y/usb-serial-for-android#341]
Hello, I have recently used your source, but I found an issue that the USB connection is always lost in Android 8.1.

Is there any way to solve this problem?

**Comment by kai-morich** [comment]
I am not aware of general issues with Android 8.1

Typically it's an issue with the hardware or android kernel of your Android device or an issue with your USB device or a combination of both devices, e.g. power usage is to high
