### ISSUE TITLE
On New Data method issue

### ISSUE THREAD

**Issue by dinak1989** [mik3y/usb-serial-for-android#348]
Im trying to fetch data using USB connection mode and but only half the data is receiving in onNewData method

For Eg

1.046KG is the actual value and we getting .1.046 for the first time and second time KG value

**Comment by kai-morich** [comment]
see https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time
