### ISSUE TITLE
The call to setThreadPriority appears to have no function

### ISSUE THREAD

**Issue by gairmuse** [mik3y/usb-serial-for-android#349]
https://github.com/mik3y/usb-serial-for-android/blob/cbed086279555ec4f2e4370d68eeeb2911104dcb/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/util/SerialInputOutputManager.java#L171

Should this be `Process.setThreadPriority()`?

**Comment by kai-morich** [comment]
you're right. `Process` got lost when extracting the prio from my SerialUsbTerminal app
