### ISSUE TITLE
Problems with bidirection sending/recieving with CdcAcmSerialDriver 

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#35]
_From [mpthomp...@gmail.com](https://code.google.com/u/103258355507046191582/) on August 21, 2013 01:53:33_

Using the latest code from git, I'm attempting to use the CdcAcmSerialDriver with an Android Nexus 7 (Android 4.3) tablet and an Arduino Mega with ROS (Robot Operating System) running ROS Serial protocol between the two devices. As long as I make sure that protocol packets are sent exclusively in one direction or the other (ie. not sending and receiving at the same time) things run fine.  

However, very soon after I allow packets to flow in both directions asynchronously I'll very quickly get an error with the mConnection.bulkTransfer() in the write() method returning less than zero and an exception being thrown which aborts the running of the SerialInputOutputManager.  The exception text is:

Run ending due to exception: Error writing 134 bytes at offset 0 length=134

Any ideas on what things I might try to get high speed bi-directioal transfer of data packets over the serial connection?

I'm going to try reducing the amount of data that bulkTransfer() will try to send or receive at one time or perhaps which to the UsbRequest interface which should it's issue with not returning how many bytes received being fixed in Android 4.2.  However, I thought others might have already found a solution.

Mike Thompson

_Original issue: http://code.google.com/p/usb-serial-for-android/issues/detail?id=35_

**Comment by micolous** [comment]
I had a similar problem with a CdcAcm device -- it turned out that `UsbSerialPort.read` was not filling my buffer.  I had to call it multiple times until my buffer was actually full, and all the data was read from the device, before continuing with a write.

The `read()` appeared to be blocking on newline characters in the stream, when all the messages I was passing were binary and of a fixed length.

**Comment by kai-morich** [comment]
you should use latest version that has UsbRequests API instead of bulkTransfer
