### ISSUE TITLE
send data main thread block

### ISSUE THREAD

**Issue by evil123** [mik3y/usb-serial-for-android#356]
1.send data main thread block

**Comment by kai-morich** [comment]
you can send in a different thread with something like

    writeExecutor = Executors.newSingleThreadExecutor();
    ...
    writeExecutor.execute(() -> {
        try {
            usbSerialPort.write(data, 0);
            mainLooper.post(() -> { /* ok handler */ });
        } catch (Exception e) {
            mainLooper.post(() -> { /* error handler */ });
        }
    });
