### ISSUE TITLE
can it Write String value instead of byte array to serial ?

### ISSUE THREAD

**Issue by wenfengzhaox** [mik3y/usb-serial-for-android#357]
I was wondering that is there any way that I can send String instead of byte array so that my program can read data and match it with my string.
eg:
usbSerial.write(firstDigit,1000);  // String firstDigit;

**Comment by kai-morich** [comment]
use `str.getBytes()`

**Comment by wenfengzhaox** [comment]
yes i made the mistake, Thank u ~

**Comment by wenfengzhaox** [comment]
> use `str.getBytes()`

yes i made the mistake, Thank u ~
