### ISSUE TITLE
Is there any monitor about USB serial port plug operation

### ISSUE THREAD

**Issue by chenjiazhi1014** [mik3y/usb-serial-for-android#360]
Is there any monitor about USB serial port plug operation

**Comment by kai-morich** [comment]
you can get notified on new devices connected:
https://github.com/mik3y/usb-serial-for-android/blob/73ef6c5b5333d27a2f295d4e952d3a5c8cd14a04/usbSerialExamples/src/main/AndroidManifest.xml#L26
https://github.com/mik3y/usb-serial-for-android/blob/73ef6c5b5333d27a2f295d4e952d3a5c8cd14a04/usbSerialExamples/src/main/java/com/hoho/android/usbserial/examples/MainActivity.java#L37

**Comment by chenjiazhi1014** [comment]
okay, thank you
