### ISSUE TITLE
Can't get data because the phone detected Arduino as charger

### ISSUE THREAD

**Issue by lythamhoa** [mik3y/usb-serial-for-android#370]
I've used mik3y for my app get data from Arduino Leonardo via USB, it's very good but when I reboot my phone, the phone get the power from Arduino USB port as charger instead of the Host. I have reset the Arduino but can't solve the problem. Only one way to solve it's disconnect then reconnect USB cable.
Anyway help!

**Comment by kai-morich** [comment]
reboot behavior is not controllable by this library

**Comment by lythamhoa** [comment]
Anyway to help? my project will run 12/24 and it'll start at
5:00AM everyday.

**Comment by kai-morich** [comment]
reboot behavior documented here: https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#How_to_persist_USB_permission
