### ISSUE TITLE
is this possible? Computer-android device interconnection

### ISSUE THREAD

**Issue by dkati** [mik3y/usb-serial-for-android#371]
Good evening.

Can i somehow write a python script that writes to a USB some raw data, and read them with my mobile device using cable ?

like fake-COM port or something...

**Comment by kai-morich** [comment]
this library only offers Java (and Kotlin) API for serial devices on android side. 
On the computer side the OS (Windows, Linux) already provides virtual COM ports.

**Comment by dkati** [comment]
yea i know what you say . my main question is how can i simply send a serial raw data (like a raw string) from i.e. a python script and make my device read it.i didnt manage to do it. 

any ideas/walkthroughs??

**Comment by kai-morich** [comment]
I use https://pypi.org/project/pyserial/

**Comment by dkati** [comment]
i also did it. which COM should i use? how can i know which COM is "connected" to the USB that my device is attached?

**Comment by kai-morich** [comment]
on Windows i use hterm, on Linux i look at /dev directory and compare device attached vs. non-attached to figure out the choosen port

**Comment by dkati** [comment]
I still understand how to do it windows side. Mind give me more details?

**Comment by kai-morich** [comment]
on Windows you could look at device manager control panel, or use some terminal app like https://www.der-hammer.info/pages/terminal.html that shows the available serial ports

**Comment by dkati** [comment]
i still cant figure out how to send raw string "hello" from hterm (windows) and read it at my android app via USB cable

i tried the example

**Comment by kai-morich** [comment]
did you connect your windows PC and android phone with a 'normal' USB cable?

**Comment by dkati** [comment]
my mobile device is a oneplus5. its connected with type-C USB. and the computer's usb is a normal usb.

i found my device's product and vendor id

**Comment by kai-morich** [comment]
with a 'normal' USB cable your phone is only in _slave_ mode. 
To use _host_ mode and serial transfer you have to use an USB-to-serial cable / module.

**Comment by dkati** [comment]
that means that i can only read device's stuff FROM computer. Not vice verse.

**Comment by kai-morich** [comment]
exactly

**Comment by dkati** [comment]
perfect. let me find the OTG and usb-serial and i will report back.

**Comment by dkati** [comment]
i have otg but... that "usb-to-serial" is an actual SERIAL cable. cant be connected to PC.

**Comment by dkati** [comment]
well...i cant understand the philosophy around that. all i wanted is 

- a python script that sends a string via USB to mobile
- mobile reads it and prints it.
mobile uses TypeC USB for connections

When that would be done, i would like to connect a GPS handheld connected with serial cable


For now i didnt manage to do even the first one...i abandon :(
