### ISSUE TITLE
Failed to receive binary data with Android

### ISSUE THREAD

**Issue by Suzumushi724** [mik3y/usb-serial-for-android#372]
What I want to do is sending 42 bytes binary data from mbed LPC1768 to my Android smartphone. The code I use is as follows.

    usbIoManager = new SerialInputOutputManager(port,musbListener);
    final ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(usbIoManager);

As you can see, a serial port listener is set. "musbListener" implements SerialInputOutputManager.Listener. The callback function (a musbListener's method) is as shown below.

    @Override
    public void onNewData(final byte[] DataBuff) {
        Log.d("DataBuff",DataBuff.toString());
        final float[] Data = decode(DataBuff);
        ...
    }

Let's see Logcat.

`D/SerialInputOutputManager: Read data len=14`
I expect for Android to receive full 42 bytes data, but only 14 bytes are received.

Please tell me what I should do to solve this problem.

**Comment by kai-morich** [comment]
please check FAQ [1](https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#My_device_is_connected_but_I_receive_no__wrong_data) and [2](https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time)

**Comment by Suzumushi724** [comment]
Thank you.
