### ISSUE TITLE
Communicate with Raspberry Pi

### ISSUE THREAD

**Issue by PemmasaniRajesh** [mik3y/usb-serial-for-android#376]
I've a requirement to communicate with Raspberry Pi from android app through USB serial communication. 

Can I use this project for that purpose ?

**Comment by kai-morich** [comment]
Yes. 

When using one of the usual serial breakout boards, you should use one that supports 3.3V for the IO lines, else you would need an additional level shifter.

**Comment by PemmasaniRajesh** [comment]
I've used this to connect android app with Raspberry Pi. My Pi USB port has 5V. Whenever I connect the sample app to the PI, only android.hardware.usb.action.USB_STATE is firing two times, USB_DEVICE_ATTACHED event hasn't fired atleast once. 

Do you've any idea about this ?
