### ISSUE TITLE
is it possible to persist USB permission even after rebooting device ?

### ISSUE THREAD

**Issue by mandipkanjiya** [mik3y/usb-serial-for-android#378]
As of now as we reboot device it ask for permission again and we want that as persisting permission. 

is it possible ?

**Comment by kai-morich** [comment]
I don't know if this is possible. Please try with `directBootAware` as recommended [here](https://issuetracker.google.com/issues/77658221)

**Comment by kai-morich** [comment]
see answer in wiki: https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#How_to_persist_USB_permission
