### ISSUE TITLE
Download 222M File Failed In 37M

### ISSUE THREAD

**Issue by sunyiyan** [mik3y/usb-serial-for-android#381]
Usb convert to cdcacm,but always failed in 45*1024*863,always failed ofs == 45*1024*862+(45*1024*0.75),once bytes is 90,
readTimeout 0,buffer size is 1024*4

**Comment by sunyiyan** [comment]
want get reply quick

**Comment by sunyiyan** [comment]
stm32 f6 and android device

**Comment by sunyiyan** [comment]
use java

**Comment by kai-morich** [comment]
what is the exact exception / error message?

Your initial post is hardly readable as * is used for markdown formatting, only in the plain text preview in my mail program i was able to understand. please update.

**Comment by sunyiyan** [comment]
Usb convert to cdcacm,but always failed in 1/3 offset.received 200M Files,once bytes received 90.
