### ISSUE TITLE
App falls down with ProbeTable

### ISSUE THREAD

**Issue by SunSayIsCool** [mik3y/usb-serial-for-android#382]
When I start my service for CDC device port listening it falls down with this error:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/hoho/android/usbserial/driver/ProbeTable;

Can you advice me how to fix it?

**Comment by kai-morich** [comment]
which version of the library do you use? do you compile it yourself?
Since v2.1.0 a [proguard-rules.pro entry](https://github.com/mik3y/usb-serial-for-android/blob/cd83951bd14031ff87f601acf2f72df38330cbbd/usbSerialForAndroid/proguard-rules.pro#L1)  should prevent elimination of classes.

**Comment by SunSayIsCool** [comment]
I'm using 3.4.2 version and add to my project by implementing dependency in Gradle

**Comment by kai-morich** [comment]
please provide exception call stack
