### ISSUE TITLE
Unnecessary output to logcat

### ISSUE THREAD

**Issue by janimm** [mik3y/usb-serial-for-android#389]
On each write to serial, logcat message is outputted

    D/CommonUsbSerialPort: Wrote #/# offset #/# timeout ###

This is on version 3.4.2.

Not a big problem but unnecessarily floods the logcat.

**Comment by kai-morich** [comment]
with `adb shell setprop log.tag.CommonUsbSerialPort INFO` you can reduce the logging level since Android 8.0

**Comment by janimm** [comment]
I'm aware of that. Problem to my opinion is that this unnecessarily floods the log on released software. I'd prefer a function that would toggle log output on/off.

**Comment by kai-morich** [comment]
could be solved similar to this: 
https://github.com/mik3y/usb-serial-for-android/blob/d3198793861db418ee1ac33ef929d1ab49a8d878/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/util/SerialInputOutputManager.java#L25

**Comment by janimm** [comment]
That would be perfect solution if you could add this to a future release.
