### ISSUE TITLE
Omap 5912 Connection Error

### ISSUE THREAD

**Issue by DaniPale80** [mik3y/usb-serial-for-android#390]
Hello mik3y,

First of all, thanks a lot for this amazing work. It's really impressive.
Hovewer, I have Omap 5912 OSK board and even i have defined my pid(0x1234)-vid(0x8765), i'm still having trouble like "connection error: No control Endpoint". My devices endpoints shoud be 0x01 and 0x81. Do you have any suggestion for my problem?

Thanks in advance
Dani

**Comment by kai-morich** [comment]
how did you connect your port: USB or RS232?
If USB, then you have to run some software that acts as server for USB CDC protocol.

**Comment by DaniPale80** [comment]
Thank you..
