### ISSUE TITLE
Does this library support Smart Card readers?

### ISSUE THREAD

**Issue by ghostravenstorm** [mik3y/usb-serial-for-android#391]
Not really an issue. Just a question.
Does this library support Smart Card reader like this one: https://www.identiv.com/products/logical-access-control/smart-card-readers/contact/scr3310v2/

I have in the past used this library to communicate with ADAFruit devices on Android https://www.adafruit.com/
Those devices are basically Ardunio devices, so I added them using the probe table like so `customTable.addProduct(0x239a, 0x800c, CdcAcmSerialDriver.class);`

So with this Smart Card reader, I tried adding these products:
```
ProbeTable customTable = new ProbeTable();
customTable.addProduct(0x04e6, 0x5116, CdcAcmSerialDriver.class);
customTable.addProduct(0x04e6, 0x5116, Ch34xSerialDriver.class);
customTable.addProduct(0x04e6, 0x5116, Cp21xxSerialDriver.class);
customTable.addProduct(0x04e6, 0x5116, FtdiSerialDriver.class);
customTable.addProduct(0x04e6, 0x5116, ProlificSerialDriver.class);
UsbSerialProber prober = new UsbSerialProber(customTable);
```
I did an entry for each driver class because I'm not sure which one this USB Smart Card reader is.

It detects the device just fine, but when it comes actually communicating with it, I get the following error
`ControlTransfer with value 0x0 failed: -1`

I then tried the Usb Serial Terminal (that uses this library), and tried the different avaliable drivers. All of them returned some connection error.
```
Connection failed: controlTransfer failed
Connection failed: Failed send cmd [init #1]
Connection failed: Control transfer failed 0 / 1 -> -1
Connection failed: Reset failed: result -1
Connection failed: ControlTransfer 0x8 failed: -1
```

So I'm guessing at this point this library doesn't support whatever communication protocol this Smart Card reader uses.
I'm here just confirming if that is the case.

**Comment by kai-morich** [comment]
No. Looks like smart cards use different USB commands.
