### ISSUE TITLE
Does this support 9bit data communication 

### ISSUE THREAD

**Issue by dmsherazi** [mik3y/usb-serial-for-android#397]
I wanted to know if this could be used for 9 bit data no parity communication

**Comment by kai-morich** [comment]
this is not supported. [Here](https://github.com/mik3y/usb-serial-for-android/blob/896b242be02473f2a43330682c0b2af29065bab8/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/UsbSerialPort.java#L27) you can find supported values for `setParameters`.
