### ISSUE TITLE
Support USB to RS232 on Android system ？

### ISSUE THREAD

**Issue by wangjianxiang** [mik3y/usb-serial-for-android#400]

**Comment by kai-morich** [comment]
please provide a detailed description

**Comment by dotnethome** [comment]
Support UART on Android system ？

**Comment by kai-morich** [comment]
the library does not support native UART ports like /dev/ttyS0

**Comment by wangjianxiang** [comment]
oh , The serial port of my hardware device is /dev/ttyS1 ， now ， i know , thinks you 。I want to collect device data through native UART ports on the app，Is there any other way？

**Comment by kai-morich** [comment]
you very likely need rooted device, some C code, ... to access /dev/ttyS1

**Comment by wangjianxiang** [comment]
oh i know , thank you, i try it
