### ISSUE TITLE
Is there a way to get the number of available bytes in the read buffer without actually reading?

### ISSUE THREAD

**Issue by SparkyTD** [mik3y/usb-serial-for-android#405]
Some other serial libraries use an internal buffer, and they expose an API for the user to peek at the number of available bytes in this buffer. (e.g. `SerialPort.BytesToRead` in C#, `SerialPort.bytesAvailable()` in jSerialComm). Is something like this possible with this library? I can't see any relevant methods in the `UsbSerialDevice` class other than `read` and `write`, but maybe I'm missing something.

**Comment by kai-morich** [comment]
There is no buffering in this library. It's also not possible to peek into USB transfers. If you do not want to allocate to much memory, you can do partial read with a buffer of size `port.getReadEndpoint().getMaxPacketSize()` as mentioned in [FAQ](https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#How_to_size_the_codereadcode_buffer)
