### ISSUE TITLE
Add note about setDTR() for Arduino

### ISSUE THREAD

**Issue by 4ntoine** [mik3y/usb-serial-for-android#41]
According to the description it can be reset using:
* open
* set baud rate 1200
* close

http://arduino.cc/en/Main/arduinoBoardMicro

It works in pure java with RxTx library but it does not work on Android with this lib.
The same problem with Arduino Leonardo board

**Comment by rohanlal217** [comment]
so what is the solution to this problem? I'm trying to get milk3y to work with a leonardo

**Comment by mik3y** [comment]
Closing obsolete issue - this is now [in the troubleshooting wiki](https://github.com/mik3y/usb-serial-for-android/wiki/Troubleshooting#i-am-using-an-arduino-uno-sparkfun-pro-micro-or-other-arduino-and-if-serial-doesnt-work).
