### ISSUE TITLE
Use of CPU with 115200 baudrate.

### ISSUE THREAD

**Issue by elioscordo** [mik3y/usb-serial-for-android#414]
Hello,
thank you for the great lib! 
I am on api 23 and java 8 with 115200 baudrate.

The processor gets stuck and the phone unresponsive:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/477426/153623751-05a30fba-9ee7-4335-90d1-dde8f524db76.png">

Any advice? Does it make sense ? It maybe something else, I am a newbie.

Thank you!

**Comment by kai-morich** [comment]
it's ok that the code waits there until new data is available, but as the SerialInputOutputManager runs in a separate thread, it shouldn't block your App.

**Comment by elioscordo** [comment]
Thank you Mike, 
you are a legend! So I have basically copied you terminal code and tweaked a bit. 
It is possible that I do not stop the service correctly so there are some hanging threads.
I will try to make a new simpler version without the service but for now I can tell that the UI gets unresponsive when data is available to read. 
It's a a super hobby project and I was having fun until now, now it's time to actually learn your code. Thank you!

Cheers,
Elio
