### ISSUE TITLE
Data collision

### ISSUE THREAD

**Issue by Sam1596** [mik3y/usb-serial-for-android#420]
I’m using two CDC ports with your CrossoverTest approach.  Everything is working as expected until both ports are receiving at the same time.  A data collision results in jumbled data.  Android 11.  Any thoughts?

**Comment by kai-morich** [comment]
with [b853ac7](https://github.com/mik3y/usb-serial-for-android/commit/b853ac773c413b4c6fef56681b4ac5a96047fe5e) i created a test for concurrent access to multi-port devices. Works without issues. 
How do you separate the received data?

**Comment by Sam1596** [comment]
Received data contains a tag, so it is easy to separate.

Your version works as expected.  Thanks!
