### ISSUE TITLE
How to access native serial port available on Raspberry Pi?

### ISSUE THREAD

**Issue by priyeshtantrasoft** [mik3y/usb-serial-for-android#421]
I'm trying to access native serial port on Raspberry Pi 4 running Emteria OS, but it's failing to detect as deviceList is blank when no USB devices are connected.. I tried this library with FT board and it worked perfectly fine. Help me in accessing the Native Serial Port of Raspberry pi.

**Comment by kai-morich** [comment]
this library is only for USB to serial adapters. Please check Android or Emteria OS documentation on how to access native serial ports.
