### ISSUE TITLE
prolific vid_067B pid_23c3

### ISSUE THREAD

**Issue by WanManito** [mik3y/usb-serial-for-android#433]
Is this chip supported in the latest version? Looking forward to your reply，I saw this question raised earlier

**Comment by WanManito** [comment]
The new version is tested and still doesn't seem to support it

**Comment by kai-morich** [comment]
I have a working PL2303GC, but looks like your PL2303GT is not correctly detected. Distinguishing classic PL2303 and PL2303G* looks tricky, as also the Linux kernel has ongoing work there. 

Please post the `rawDescriptor` value used here: https://github.com/mik3y/usb-serial-for-android/blob/cf9bada887479a11a2de3e62102c81f3904b4e97/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/ProlificSerialDriver.java#L293

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/168768764-1f939752-4ace-4fa2-9cb7-c3bcf5be964c.png)
------
Do you want me to print the value "rawDescriptors"? I can use it normally according to this man's operation, but I don't know if it affects other operations

**Comment by kai-morich** [comment]
please post log output created with latest version f997a8b68ab5a53ad4cd34ec1ef44ab609dcc020

**Comment by kai-morich** [comment]
duplicate to #439
