### ISSUE TITLE
Cannot open a port at port.open()

### ISSUE THREAD

**Issue by Suzumushi123** [mik3y/usb-serial-for-android#434]
Hi, I'm using ESP32 to connect my Android phone. When I connect these devices and try to transit data, it throws an exception that means failng to open a port. The following is what I tried.
1. I used ProbeTable to resister vendor-id and product-id of ESP32.
2. I checked the port that I'm tring to open is not null.
3. I tried the same situation with Arduino Uno, which results in success of opening the port.

Would you give me some hints to solve these issues?

**Comment by kai-morich** [comment]
please verify that your ESP32 runs software that initializes & uses USB CDC communication
