### ISSUE TITLE
couldn't resolve mik3y/usb-serial-for-android. Android Studio went looking in the jcenter but failed to find it

### ISSUE THREAD

**Issue by meganmeiyang** [mik3y/usb-serial-for-android#437]
## Root gradle:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/1858427/179400850-25c317ee-4f60-45a3-ac57-70934dba1c9b.png">

 ## App dependencies:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/1858427/179400916-4fa96913-13f2-4a06-8120-5762ed0c8e4f.png">

## Got error message:
```
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.mik3y:usb-serial-for-android:v3.4.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/mik3y/usb-serial-for-android/v3.4.5/usb-serial-for-android-v3.4.5.pom
       - https://repo.maven.apache.org/maven2/com/github/mik3y/usb-serial-for-android/v3.4.5/usb-serial-for-android-v3.4.5.pom
       - https://jcenter.bintray.com/com/github/mik3y/usb-serial-for-android/v3.4.5/usb-serial-for-android-v3.4.5.pom
     Required by:
         project :app
```

**I looked it up in jitpack, the configuration is absolutely correct.**

<img width="718" alt="image" src="https://user-images.githubusercontent.com/1858427/179400989-e49ade05-caac-448e-a6cf-eea0b97ccb08.png">

With or without "v" (in your readme), result is the same - still failed.

## Tried:
- restarted the android studio
- clean project
- rebuild

**Comment by kai-morich** [comment]
The jitpack repo has to be added in `allprojects` not `buildscripts`

**Comment by meganmeiyang** [comment]
got it. solved...
