### ISSUE TITLE
how can i change stopbit and PARITY

### ISSUE THREAD

**Issue by zxy243153431** [mik3y/usb-serial-for-android#438]
my project neet to change these two attribute when in data communication.
For example : 
port.setParameters(9600, 8, UsbSerialPort.STOPBITS_1, UsbSerialPort.PARITY_EVEN);
...write some data
port.setParameters(9600, 8, UsbSerialPort.STOPBITS_2, UsbSerialPort.PARITY_NONE);
...write some data
...read bytes
port.setParameters(9600, 8, UsbSerialPort.STOPBITS_1, UsbSerialPort.PARITY_EVEN);
.....write some data
....read bytes

i wrote code like this ,but the result not working as expected.
i want to ask how can i do that stopbit and PARITY can be changed in data communication.

**Comment by kai-morich** [comment]
parameters can be changed with setParameters when the connection is open, e.g. tested [here](https://github.com/mik3y/usb-serial-for-android/blob/f8e76c9b3b58e0ae4005215d1bb2d9c4cea401d6/usbSerialForAndroid/src/androidTest/java/com/hoho/android/usbserial/DeviceTest.java#L609). 
maybe you have to wait until old data is fully read/written

**Comment by zxy243153431** [comment]
> parameters can be changed with setParameters repeatedly when the connection is open, e.g. tested [here](https://github.com/mik3y/usb-serial-for-android/blob/f8e76c9b3b58e0ae4005215d1bb2d9c4cea401d6/usbSerialForAndroid/src/androidTest/java/com/hoho/android/usbserial/DeviceTest.java#L609). maybe you have to wait until old data is fully read/written

i tried  and it runs success! thank you very much.
