### ISSUE TITLE
I wonder how to process the data received in hexadecimal and control and store it in decimal.

### ISSUE THREAD

**Issue by jongjun307** [mik3y/usb-serial-for-android#442]
Hello. It's working fine but  I wonder how to process the data received in hexadecimal and control and store it in decimal.

The final goal is to receive data in seconds and check it in real time.

Thank you.

**Comment by kai-morich** [comment]
the data is received as byte[] and only converted to hex for display in the example app [here](https://github.com/mik3y/usb-serial-for-android/blob/5bb8db02d5a6f2db32522ce602a6dd7d791de083/usbSerialExamples/src/main/java/com/hoho/android/usbserial/examples/TerminalFragment.java#L297)
