### ISSUE TITLE
teacher... help me plz...

### ISSUE THREAD

**Issue by kmd2410** [mik3y/usb-serial-for-android#446]
Hello, teacher. I have a question.
I used a nice and beautiful sample of your teacher.
Connected usb is also recognized.
However, we receive data only when the usb is initially connected, and we do not receive data afterwards.
Which part should I review?
I need your advice.
Thank You
![pic](https://user-images.githubusercontent.com/75105354/183022250-cb7dec20-1792-41b5-84ba-3e0c92da6534.jpg)
.

**Comment by Loopjj** [comment]
Make sure that the device sends data normally
