### ISSUE TITLE
how to regex, serial read buffers

### ISSUE THREAD

**Issue by kashi022410** [mik3y/usb-serial-for-android#448]
Dear, Mr
I try read data from usb serial port and it is like (23610). Then convert it to string then split "(" ")" but it crashes. Would you have any idea?
![image](https://user-images.githubusercontent.com/27668808/188869380-d4a707b5-eb42-489a-9af9-1db8eab4e30f.png)

**Comment by kai-morich** [comment]
Not necessarily all bytes arrive in a single message. You should buffer until complete, see https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time
