### ISSUE TITLE
"Queueing USB request failed" in Realme C11 running android 11.

### ISSUE THREAD

**Issue by yureka** [mik3y/usb-serial-for-android#452]
When try to queue the reading request, UsbRequest is throwing following error

W/SerialInputOutputManager: Run ending due to exception: Queueing USB request failed
    java.io.IOException: Queueing USB request failed
        at com.hoho.android.usbserial.driver.CommonUsbSerialPort.read(CommonUsbSerialPort.java:200)
        at com.hoho.android.usbserial.driver.CommonUsbSerialPort.read(CommonUsbSerialPort.java:169)
        at com.hoho.android.usbserial.util.SerialInputOutputManager.step(SerialInputOutputManager.java:225)
        at com.hoho.android.usbserial.util.SerialInputOutputManager.run(SerialInputOutputManager.java:203)
        at java.lang.Thread.run(Thread.java:923)

**Comment by caoluming** [comment]
I have the same problem, how did you solve it? thanks

**Comment by yureka** [comment]
When the USB Device has hub, UsbRequest is throwing the above error. Without hub, able to read properly.

**Comment by caoluming** [comment]
Thank you for your suggestion, I also show that it is related to the hardware here.

**Comment by caoluming** [comment]
This is the case with some devices I've detected here, and the frequency of that device's appearance is uncertain. That device, which had never appeared before, appeared suddenly, and the frequency gradually increased. After restarting the MCU, the situation improved, but the device still had this situation, it felt like the cause of the MCU.

**Comment by kai-morich** [comment]
I mentioned some reasons here: https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#My_device_sporadically_disconnects_with_codeQueueing_USB_request_failedcode

**Comment by caoluming** [comment]
Yes, it is indeed a hardware problem on my side
