### ISSUE TITLE
Deleted tags causing broken build? 

### ISSUE THREAD

**Issue by rojepp** [mik3y/usb-serial-for-android#456]
It seems a bunch of old tags were deleted, breaking our build. In a project, we depend on v2.1.0 of this library. 
At least I think that's what causing this. Please don't delete tags. ;)

**Comment by kai-morich** [comment]
which kind of tags are missing. in github and local repo I still see all tags.

**Comment by rojepp** [comment]
Sorry, my bad, I missed the last page lol. I guess jitpack is just having a bad day.
