### ISSUE TITLE
Detect end of stream with onNewData

### ISSUE THREAD

**Issue by emendo-web** [mik3y/usb-serial-for-android#462]
Hello,

Thank you for this package.

From what I could see of this package how can I know that my data has all arrived before processing it?

With the onNewData method I receive data substitution

Would there be a solution to know when all the bytes received?

InputStream returned -1 if reading data is complete

Or is the only solution to detect a delimiter character and close the stream when found ?

Thanks,
Cyril

**Comment by kai-morich** [comment]
see https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#when-reading-a-message-why-dont-all-bytes-arrive-at-the-same-time
