### ISSUE TITLE
no driver

### ISSUE THREAD

**Issue by GanZzaz** [mik3y/usb-serial-for-android#465]
Please teach me how to solve if "no driver" appears under "actuvutt_main". I have added "pid" and "uid" to "device_filter.xml"

**Comment by GanZzaz** [comment]
If you add in "CustomProber" it shows no connection

**Comment by kai-morich** [comment]
device_filter is only for App auto-start. You have to add correct VID + PID to custom prober

**Comment by GanZzaz** [comment]
Where do I need to add to

**Comment by kai-morich** [comment]
e.g. [here](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialExamples/src/main/java/com/hoho/android/usbserial/examples/CustomProber.java)

**Comment by GanZzaz** [comment]
我在这里也添加了，能够进入通信界面，可是发送时，弹窗显示"not connected"

**Comment by GanZzaz** [comment]
I also added here, you can go to the communication screen, but when you send it, it pops up saying "not connected."

**Comment by GanZzaz** [comment]
I added here, I can go to the communication screen, but I can't send it, it pops up and says "not connected."

**Comment by GanZzaz** [comment]
The connected in TerminalFragment.java is false

**Comment by tombrooks1994** [comment]
I am having the same issue with a CP210x device. I am trying to get it to connect but having no luck @kai-morich are you able to advise?
