### ISSUE TITLE
怎么判断指令发送成功与否？

### ISSUE THREAD

**Issue by 592308980** [mik3y/usb-serial-for-android#471]
我需要实现异步发送指令，然后实时监听收到的数据；
一对一的数据发送和监听，比如客户端发送一条123，服务端收到指令后返回给我一串数据给我，用于标记此次通信结束；
这种情况怎么实现？

**Comment by kai-morich** [comment]
Please check recommendations at https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#user-content-When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time

**Comment by zongren** [comment]
add unique id to each command
