### ISSUE TITLE
com.android.usbserial.driver.SerialTimeoutException: Error writing 64 bytes at offset 0 of total 64, rc=-1

### ISSUE THREAD

**Issue by WanManito** [mik3y/usb-serial-for-android#474]
After about 20 hours of continuous operation, the communication was suddenly interrupted and the following error was sent again:
“com.android.usbserial.driver.SerialTimeoutException: Error writing 64 bytes at offset 0 of total 64, rc=-1”，

Serial port chip information is as follows: “prolificSerialDriver_vid=1659&pid=9155”.

When an error occurs, the usb device is connected again and cannot be connected. Finally, the USB device is restored to normal

**Comment by WanManito** [comment]
Disconnect and plug in the usb device to restore normal

**Comment by kai-morich** [comment]
to my experience all else is better then prolific chips. please try a different one
