### ISSUE TITLE
Suggestion: Would be great to a chart plotter as well

### ISSUE THREAD

**Issue by jacky4566** [mik3y/usb-serial-for-android#475]
Trying to debug a field PID device. We like to use this app for changing setting but have a graphing function would be amazing for tuning PID devices in the field.

**Comment by kai-morich** [comment]
this is a library with a simple demo app. more sophisticated visiualization is out of scope here.
If someone knows a an app, please add [here](https://github.com/mik3y/usb-serial-for-android/wiki/Projects-Using-usb-serial-for-android)
