### ISSUE TITLE
I didn't create a full jar

### ISSUE THREAD

**Issue by mistermax80** [mik3y/usb-serial-for-android#479]
Ho, I didn't create a full jar by gradle command.
In case It is not possible, You could sendme a fulljar?

![WhatsApp Image 2023-03-17 at 23 20 31](https://user-images.githubusercontent.com/15519907/226165361-618a3920-8c0c-4197-82e2-e87f0e2dafed.jpeg)

**Comment by kai-morich** [comment]
you can download from jitpack, e.g. https://jitpack.io/com/github/mik3y/usb-serial-for-android/v3.5.1/usb-serial-for-android-v3.5.1.aar
