### ISSUE TITLE
Texas Instruments TIVA TM4C123G

### ISSUE THREAD

**Issue by shibshib** [mik3y/usb-serial-for-android#48]
Texas Instruments' TIVA launchpad is becoming increasingly popular.

I am trying to transfer sensor sample readings from a Tiva launchpad + senshub booster pack to an android device. I was hoping to run the usb example provided in this project, and make use of the usb serial example provided in the tivaware 2.01 release on the microcontroller to communicate between the two. It looks like they should almost fit together, but I've run into a problem.

hen I tried to send a control transfer to the TIVA to set the UART properties (to test the example), the TIVA board starts spamming NULL characters through the debug USB port. After further investigation I've found that the UsbSerialDriver read() function spews out null characters as long as there are bytes, for some strange reason. 

My part is TM4C123GH6PM (rev1 I believe), and the example is usb_dev_serial from: C:\ti\TivaWare_C_Series-2.0.1.11577\examples\boards\ek-tm4c123gxl\usb_dev_serial

Thanks a lot!

Ala

**Comment by gnaur** [comment]
See fix in issue #112

Ralph

**Comment by kai-morich** [comment]
fixed with #166
