### ISSUE TITLE
Troubleshooting data transmission issues with a Nucleo 32 board using CDC driver

### ISSUE THREAD

**Issue by ichbinvinh** [mik3y/usb-serial-for-android#483]
Hallo Kai,

I tested it with a Nucleo 32 board (STM32). It successfully connected using the CDC driver and is able to send data. However, when I try to read data from the device (tested with all baud rates), I always receive the message "received 0 bytes". Do you think I should write a protocol for this device? Do you have any examples of protocols that I could use?

Viele Grüße,
Vinh Nguyen

**Comment by kai-morich** [comment]
Please check https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#i-am-using-an-arduino-uno-sparkfun-pro-micro-or-other-arduino-but-serialwrite-does-not-send-data
