### ISSUE TITLE
String truncation while receiving data from an Arduino Due in an App with a graph in a Canvas...

### ISSUE THREAD

**Issue by emc3las** [mik3y/usb-serial-for-android#49]
I have been using the library for communication between an Arduino Due and a tablet running Android 4.1.1. After modifying the Map<> getSupportedDevices method of the class CdcAcmSerialDriver and the class UsbId by adding the product ID "ARDUINO_DUE = 0x003d", I've got the example working. I have also replaced the message printed at the SerialConsole using HexDump.dumpHexString(data) by a  simple "new String(data)", and the short strings I've been sending from Arduino at each tenth of a second were correctly printed at the tablet secreen.

The data string truncation problem really begun when I added to my App a graph continuously updated to monitor the data received at the tablet from the Arduino through the USB Programming Port. There is any simple advice that I could follow in order to prevent this very inconveniente data truncation?

PS: The Arduino Due has also an "USB Native Port" and this one was not recognized by any of the Android Apps that I have installed in the tablet I am using.

**Comment by kai-morich** [comment]
you should use latest version that has UsbRequests API instead of bulkTransfer to avoid data loss
