### ISSUE TITLE
USB get_status request failed

### ISSUE THREAD

**Issue by WanManito** [mik3y/usb-serial-for-android#491]
version = 3.5.1

When I connect to a USB serial port with no available devices, I can connect normally, but when I close it, it will trigger the exception "java. io. IOException: USB get_status request failed", and I cannot connect all devices normally. If I connect to new available devices again, the exception "Reset failed: result=-1" will always be triggered

**Comment by kai-morich** [comment]
which device type are you using? do you get the exception from the close command?

**Comment by WanManito** [comment]
Ftdi vid = 1027，pid = 24577
prolific vid = 1659,pid = 9155,
close exception  = "java. io. IOException: USB get_status request failed"

**Comment by WanManito** [comment]
As a supplementary explanation, I used two types of USB serial devices with the same phenomenon. The testing process is as follows:
The USB port connects to Android devices, but DB9 is not connected to any devices. It can open the connection normally, and closing it again will trigger an exception, and then it cannot connect to any other devices. @kai-morich

**Comment by kai-morich** [comment]
does it fail with FTDI or Prolific device? Prolific devices are known for unstable connection.

**Comment by WanManito** [comment]
Hello, both devices have been tested and this phenomenon is inevitable. I'm not sure if I have described it clearly @kai-morich

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/234464936-bdb868d3-38bf-4742-a755-429932ba350d.png)

**Comment by kai-morich** [comment]
when opening again, you very likely cannot reopen an existing `UsbSerialPort` object, but have to redo initialization starting with  `manager.openDevice`

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/234490593-1d184349-e7d9-402f-9821-f305745eedc2.png)

**Comment by WanManito** [comment]
I'm very sorry, because I used a USB hub to connect two USB serial devices. After repeated testing, it was a problem with the USB hub. I switched to another brand of USB hub and everything was normal. Thank you for your support

**Comment by Jai-GAY** [comment]
@WanManito 

I think is good that you share the brand, model and a picture so the rest of the users can avoid it to repeat the same questions to the developers.
