### ISSUE TITLE
no driver for device

### ISSUE THREAD

**Issue by Ranjit8298** [mik3y/usb-serial-for-android#492]
Hii @mik3y  , Please help
How to resolve this issue **no driver for device**?

**Comment by narendran12** [comment]
Hi @kai-morich @mik3y i am using the latest library. When i connect the usb pendrive is detecting and it says no driver, on tap of that i am getting error toast like no driver. Could you please help.

@Ranjit8298 Have u got any workaround for this issue?

![Screenshot_20230508_121532_USB Serial Example](https://user-images.githubusercontent.com/54102354/236753777-1a703ae4-7fa8-4d51-8260-8cb1760ac525.jpg)

**Comment by kai-morich** [comment]
your 'pendrive' is a memory device, but not a serial device, so you cannot open it with this library

**Comment by Jai-GAY** [comment]
> connect the usb pendrive is detecting
Do not quite understand why you need this app to open USB mass storage class device where all OTG phones can use the default file explorer to browse the contents.

[this app compatible-devices](https://github.com/mik3y/usb-serial-for-android#compatible-devices)
