### ISSUE TITLE
FTDI-FT232RL support? 

### ISSUE THREAD

**Issue by nerlins** [mik3y/usb-serial-for-android#497]
Sorry to make an issue. Have no other way to ask. Found a cable online with a similar chipset but it ends in an L. Would this project support that chipset?

**Comment by kai-morich** [comment]
maybe the newer device needs less external components or supports higher baud rate, but for normal usage i asume they are equivalent

**Comment by nerlins** [comment]
> maybe the newer device needs less external components or supports higher baud rate, but for normal usage i asume they are equivalent

Just wanted to let you know this chipset is working. Thanks again for this project.
