### ISSUE TITLE
CDC device with `mAlternateSetting`

### ISSUE THREAD

**Issue by Sa-f43** [mik3y/usb-serial-for-android#499]
We are using a CDC-ECM composite device, and it looks like that the CDC Ethernet Control Model can have more than one data interface associated with it for different settings. For that reason, we would end up writing into the wrong interface. This maybe an issue specific to CDC-ECM devices. 
We think If the openInterface() function in CdcAcmSerialDriver does not increment the interfaces count for repeated interface IDs then that may fix the issue. 

![image](https://github.com/mik3y/usb-serial-for-android/assets/134646649/82936230-e0df-43c5-9198-87aa0b041991)

**Comment by kai-morich** [comment]
as USB IAD descriptors are not exposed on Java level it's difficult to to group interfaces. The library already has a workaround for RNDIS interfaces. Here would have to handle the `mAlternateSettings`

**Comment by kai-morich** [comment]
please provide complete interface list.
probably could add a list of already seen `mId` and skip the the alternate interfaces

**Comment by Sa-f43** [comment]
Here is the complete interface list
![image](https://github.com/mik3y/usb-serial-for-android/assets/134646649/7c05afb1-9369-4a79-8579-638bf38ddc04)

**Comment by kai-morich** [comment]
@Sa-f43 could you provide the full USB descriptor, e.g. by adding

    Log.d("terminal","USB descriptor:\n" + HexDump.dumpHexString(usbConnection.getRawDescriptors()));
before

    usbSerialPort.open(usbConnection);
in `usbSerialExamples/src/main/java/com/hoho/android/usbserial/examples/TerminalFragment.java` ?
