### ISSUE TITLE
Not receiving any data

### ISSUE THREAD

**Issue by gautam-paliwal** [mik3y/usb-serial-for-android#500]
I am tring to communicate between android app and Xbee3. I am able to send data from android app to XBee3 but not receiving any Data from Xbee3 to android app. I have tried to implement SerialInputOutputManager.Listener and int len = port.read(packet, 1000); but none of them works

**Comment by kai-morich** [comment]
please try: https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#user-content-I_am_using_an_Arduino_Uno_Sparkfun_Pro_Micro_or_other_Arduino_but_codeSerialwritecode_does_not_send_data

**Comment by Alfaizkhan** [comment]
I'm also not getting the data in the application sometime.

I have to open application again, make a connection and then only it will work.

**Comment by Alfaizkhan** [comment]
@kai-morich 
Any solution or tips?
Why it's happening.

I get nothing in onNewData() sometimes.
