### ISSUE TITLE
purgeHwBuffers

### ISSUE THREAD

**Issue by mistermax80** [mik3y/usb-serial-for-android#501]
I use the UsbDriver (Arduino I think CDC device), and so I would like to use the purgeHwBuffers, in order to clean the buffer and resync the data flow.
Could you send me an advice to use the purgeHwBuffers?

Thanks so much.

**Comment by kai-morich** [comment]
With this function you can discard data in send/receive buffers in your serial device, but some data could already be received by your Android device, so you have to try if it really works for your purpose.

**Comment by kai-morich** [comment]
Yep, not supported by CDC devices
