### ISSUE TITLE
Could noread & write endpoints error

### ISSUE THREAD

**Issue by GanZzaz** [mik3y/usb-serial-for-android#502]
Hello author, I have a connection failed: Could noread & write endpoints error, how should I solve it

**Comment by kai-morich** [comment]
please provide more details, e.g. used serial device type, exact error, ...

**Comment by GanZzaz** [comment]
I use the chip GD32F103CBT6. The USB pin VID is 28E9PID is 128A

**Comment by GanZzaz** [comment]
![image](https://github.com/mik3y/usb-serial-for-android/assets/102198992/799f8eb6-929e-4415-924b-3f79547b79a0)

**Comment by kai-morich** [comment]
Your device very likely was detected as CDC device but maybe your software on the GD32 is incomplete
