### ISSUE TITLE
Cannot resolve BuildConfig symbol

### ISSUE THREAD

**Issue by amarz2195** [mik3y/usb-serial-for-android#508]
Hello guys. I am using the github project to build a serial connection.
I use the gtihub as a module imported into my project. Have been following the issue that is resolved by other users. It's working at first. But when I import it inside the project, the same problem occurs which is 'can't find symbol class BuildConfig'. do help me.
![Screenshot 2023-07-04 110540](https://github.com/mik3y/usb-serial-for-android/assets/133201157/d10d3e01-8c78-464d-a0b6-a6389d872345)
This is my error
![Screenshot 2023-07-04 110609](https://github.com/mik3y/usb-serial-for-android/assets/133201157/97ac4dd5-ecbf-4ab4-941f-67b65b98f979)
This is my buildconfig that is generated
How can I do this?

**Comment by amarz2195** [comment]
![Screenshot 2023-07-04 114138](https://github.com/mik3y/usb-serial-for-android/assets/133201157/948e2694-8150-4d44-9e6a-4d53a7e417d2)
this is the buildconfig that is generated after building the project

**Comment by amarz2195** [comment]
why I cannot import import com.hoho.android.usbserial.BuildConfig;?

**Comment by amarz2195** [comment]
I have work out the code until I only got this error
![Screenshot 2023-07-04 123413](https://github.com/mik3y/usb-serial-for-android/assets/133201157/5de3b5a3-280d-4818-be69-0a665deb3788)
help me on how to get the buildconfig. this is after i added the dependencies in the build.gradle (usbSerialExample)
the java for buildconfig is not generated automatically after adding the dependencies. why?

**Comment by kai-morich** [comment]
if your project is using gradle 8.0 you have to add the following line to `gradle.properties` file

    android.defaults.buildfeatures.buildconfig=true

**Comment by amarz2195** [comment]
thank you for the information
what does this mean?
![Screenshot 2023-07-04 135728](https://github.com/mik3y/usb-serial-for-android/assets/133201157/e3b0b455-ee28-4cf0-9672-4c8f4ffe4dd5)

**Comment by kai-morich** [comment]
I typically try build->Clean, Build->Rebuild, File->Sync-Project or File->Invalidate-Caches. Sooner or later the issue is resolved.

**Comment by amarz2195** [comment]
i have tried all the methods above, all of the method can't help in resolving the error that i get
![Screenshot 2023-07-04 145648](https://github.com/mik3y/usb-serial-for-android/assets/133201157/abf0ce79-a1c5-414c-86fa-edbea84672a3)
it says that because I have two buildconfig files. but the two is in buildconfig java is in different files. one in usbserialexample and also in usbforandroid. how can i do this?

**Comment by kai-morich** [comment]
I recommend you restart with a plain fork and then change step by step

**Comment by amarz2195** [comment]
thank you sir for the knowledge shared.
I have successfully built the project.
There's some question maybe out of the topic of usb serial for android
After successfully building the project, I tried to run the project with the built. The error shows no module for the main app
![Screenshot 2023-07-04 123413](https://github.com/mik3y/usb-serial-for-android/assets/133201157/6bffb4e8-2d36-41ae-a237-e7d682c8044d)
Please help me sir. I am new to this

**Comment by amarz2195** [comment]
thank you sir for the assist
have successfully built the project
one more question, when i try running the project, it appears that there are no module appear for the project built
![Screenshot 2023-07-05 142705](https://github.com/mik3y/usb-serial-for-android/assets/133201157/b6ab4cf5-e977-489f-b497-43236511f90e)
what should i do? 
I am new to this software.

**Comment by amarz2195** [comment]
thank you sir
