### ISSUE TITLE
Android Resource Linking Failed

### ISSUE THREAD

**Issue by amarz2195** [mik3y/usb-serial-for-android#509]
![Screenshot 2023-07-05 160106](https://github.com/mik3y/usb-serial-for-android/assets/133201157/5f4614ee-83cf-4b6c-8c24-bb398ffc20f5)
why I have an error on android:resource:@xml/device_filter?

**Comment by kai-morich** [comment]
you have to copy that file from https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialExamples/src/main/res/xml/device_filter.xml to your project

**Comment by amarz2195** [comment]
thank you sir
