### ISSUE TITLE
Probe devices based on device class

### ISSUE THREAD

**Issue by ghost** [mik3y/usb-serial-for-android#51]
There are a lot Arduino compatible devices that also should be supported. 
As Micro (pid:8037) and Freetronics (vid:26BA), Microduino etc.
Maybe have a sense add support by device class or/and interface class.
Sure some devices steel should be defined by vendor id, but in general most of them could be detected by class.

@mik3y if you need more info and/or help with testing/codding/additionali information support, please don't hesitate :+1: :)

**Comment by kai-morich** [comment]
please use a custom prober: https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices
