### ISSUE TITLE
Configure the serial communication parameters

### ISSUE THREAD

**Issue by tonnqueiroz** [mik3y/usb-serial-for-android#512]
Can anyone help me, please?

I'm trying to send CLI commands to a CISCO Router (Model C921-4P) through Kotlin code, but I'm having trouble with the penultimate step of the process.

First Driver: _com.hoho.android.usbserial.driver.ProlificSerialDriver@410e752_

I can open the connection with the device: _android.hardware.usb.UsbDeviceConnection@3be0c0d_
I get the port of the device: _ProlificSerialPort device_name=/dev/bus/usb/002/002 device_id=2002 port_number=0_
I open the port: _OK_

**BUT I CAN'T CONFIGURE THE SERIAL COMMUNICATION PARAMETERS IF THE LOGIC USED TO CONFIRM IF THIS STEP IS CORRECT...**

	// Parameters contained in the equipment manual
	val desiredBaudRate = 9600
	val desiredDataBits = 8
	val desiredStopBits = UsbSerialPort.STOPBITS_1
	val desiredParity = UsbSerialPort.PARITY_NONE

	// Configure the serial port parameters
	port?.setParameters(desiredBaudRate, desiredDataBits, desiredStopBits, desiredParity)

	// Try to read a few bytes to verify if the parameters are correctly configured
	val buffer = ByteArray(10)
	val numBytesRead = port?.read(buffer, 1000) ?: 0

	if (numBytesRead == buffer.size) {
		// The parameters are correctly configured
		Log.d("CLI", "Serial communication parameters configured correctly")
	} else {
		// The parameters are not configured correctly
		return "Error configuring the serial communication parameters"
	}

**Comment by kai-morich** [comment]
you cannot read a fixed number of bytes, see [fragmentation](https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#user-content-When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time) and [buffer size](https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#user-content-How_to_size_the_codereadcode_buffer)
