### ISSUE TITLE
Failed to resolve: com.github.mik3y:usb-serial-for-android:3.5.1

### ISSUE THREAD

**Issue by iamatulsingh** [mik3y/usb-serial-for-android#517]
I'm trying to import this in new android project with targetSdk 33 and gradle 8.0. 

I added  `maven { url 'https://jitpack.io' }` in `settings.gradle` but still getting above error.

and then

```gradle
dependencies {
    implementation 'com.github.mik3y:usb-serial-for-android:3.5.1'
}
```

Any thing that I'm doing wrong?

**Comment by kai-morich** [comment]
please check that you have added the `jitpack` line in the right gradle file and the right section as mentioned in README

**Comment by iamatulsingh** [comment]
Sorry it was idiotic question. I added jitpack wrong. Thank you very much for your time.
