### ISSUE TITLE
UsbRequestJNI﹕ close

### ISSUE THREAD

**Issue by MmingY** [mik3y/usb-serial-for-android#520]
Thanks for the library. I have a problem that after opening the USB link, the link will be closed after a period of time (1 minute to 10 minutes). Instead of closing it, I saw that the finalize method in the UsbRequest class was called. When the amount of data accepted is small, I tried 7-8 hours without problem, but when the amount of data is relatively large, this problem will occur (4 pieces of data per second, each data size is about 70B) will have problems.

**Comment by kai-morich** [comment]
please provide a call stack.
which driver are you using?
