### ISSUE TITLE
Android to Arduino physical device code upload connectivity  issue

### ISSUE THREAD

**Issue by ayushimundra30** [mik3y/usb-serial-for-android#525]
I went through your repo found useful Android USB host OTG mode enable .

I have query this is just an library to enable the USB host OTG mode in Android latest version for an serial communication . We have to add this library code in existing  project with actually do burning code to physical device Arduino using ATmega328 device driver .
 Link : https://github.com/ksksue/PhysicaloidLibrary
 Currently using above code I am getting connectivity issue . 

Please correct me if my understanding wrong or directly using your code device drivers physical boards inbuild and burn the code ? 

Regards
Ayushi Mundra

**Comment by kai-morich** [comment]
You can use both libraries for communication but only the physicaloid or other library for firmware upload. You have to try out if usb-serial-for-android library solves your communication issues. 

If your device does long lasting operations and not handle usb data in the main loop you might get data loss or other communication issues.

**Comment by ayushimundra30** [comment]
Hi Kai , 
As per suggestion ,Including the library dependencies and manifest file permission will resolve the connectivity issue cannot open device .

**Comment by kai-morich** [comment]
firmware upload is functionality on top of this library. please check physicaloid or other resources.
