### ISSUE TITLE
Sending hex string instead of [] byte

### ISSUE THREAD

**Issue by momyuke** [mik3y/usb-serial-for-android#532]
Hi i just found this tools is great, but i need my android to send the hex string instead of [] byte. Is there any work around to do this? Or this package is not supported yet to do so?

**Comment by kai-morich** [comment]
you have to convert your data to hex bytes before sending, e.g. with `HexDump.toHexString(yourByteArray).getBytes()` using `HexDump` class from this library

**Comment by momyuke** [comment]
It may be too late but thanks for the reply @kai-morich. 
It was my mistake to not know the basic first
