### ISSUE TITLE
 facing Issue in android12+ or android 13 with this library

### ISSUE THREAD

**Issue by uniqueram** [mik3y/usb-serial-for-android#533]
Everything was working fine until Android 11 but things broke afterward, The application is opening as it should in Android 13 but when the print button is pressed from the scale the application keeps on crashing Also using the external device it is hard to logcat the possible error so I am stuck here what went wrong in android 13 when print button is pressed application crashed. I think the possible error is due to USB communication when the communication is initiated it crashes.

**Comment by uniqueram** [comment]
I have tried  #494 without any success.

**Comment by uniqueram** [comment]
application crashes only when the data is sent from the scale.

**Comment by uniqueram** [comment]
@kai-morich

**Comment by kai-morich** [comment]
please provide callstack and use more specific title

**Comment by uniqueram** [comment]
As I am unable to log the problem as the application is not connected to android studio while using with the scale via USB cable so asking anyone facing issue while running this application in android 12+

**Comment by kai-morich** [comment]
You can connect adb/android-studio over wifi. Setup sometimes a bit shaky for me, e.g. USB adb connection first, then switch to tcp, but sometimes only working on newly rebooted Android device.

Does the same issue happen with https://github.com/kai-morich/SimpleUsbTerminal?

**Comment by uniqueram** [comment]
yes 
I am using this?

**Comment by uniqueram** [comment]
I have solved the issue in one place I haven't consider the pendingIntent.flag_Immutable:0; after placing this it works.
