### ISSUE TITLE
 SerialInputOutputManager decompiled byte code does not match with the source code

### ISSUE THREAD

**Issue by mfran89** [mik3y/usb-serial-for-android#536]
So I made a ticket awhile ago in regards to this #516 . I just had a chance to get back to this and I think I have figured out the issue. I am using an external library called ATAK and there is a decompiled byte code for the older version of your code in it. My background in gradle is not very strong and the issue seems to be a class conflict on the external library level. Would you have any recommendations on making my project see your external library 'com.github.mik3y:usb-serial-for-android:3.5.1' as the library to use as opposed to the one located in the ATAK library?

Thanks
Mike

**Comment by kai-morich** [comment]
you could try to limit visibility of nested library with [`implementation`](https://developer.android.com/build/dependencies#dependency_configurations) instead of `api`, or try changing the order in `dependencies` section

**Comment by mfran89** [comment]
I am currently using implementation to add the library , I tired playing with the exclude command within the implementation and that didnt do the trick either.
