### ISSUE TITLE
USB for debug and for device communication

### ISSUE THREAD

**Issue by mpiffari** [mik3y/usb-serial-for-android#542]
Hello folks and @kai-morich ,
A simple question: do you know a way to use USB connection both for debug and for connection with an external USB device?

**Comment by Jai-GAY** [comment]
[Connect to a device over Wi-Fi](https://developer.android.com/tools/adb#connect-to-a-device-over-wi-fi), this out.

**Comment by mpiffari** [comment]
Hi @Jai-GAY,
is this the only solution available? I've tried this in the past weeks, and it seems so slow (with a Xamarin forms app).

Someone has implemented an hw solution (maybe with particular cable connection)?

**Comment by Jai-GAY** [comment]
> Someone has implemented an hw solution (maybe with particular cable connection)?

Don't think so. [Power + data, yes](https://shp.ee/d8988at) . Power+ data + data, I haven't see one yet.

**Comment by kai-morich** [comment]
With external USB device the port is switched to host mode with OTG adapter. When debugging it is in slave mode with regular USB cable. I really doubt that this can be mixed.

**Comment by mpiffari** [comment]
@kai-morich thanks for your hints. 
So, how did you approach the problem? Did you use wi-fi debugging?

**Comment by kai-morich** [comment]
Yes. Use Wi-Fi debugging
