### ISSUE TITLE
USB Composite Device. Could not get read & write endpoints

### ISSUE THREAD

**Issue by diamond-61** [mik3y/usb-serial-for-android#548]
Hello! 
Hello I have "composite"
My device has 5 interfaces. There is a description in the screenshot.

When I call findAllDrivers(UsbManager) and get the driver  ```CdcAcmSerialDriver```.

Next I open the device and try to open the serialPort. ```m_serialPort.open(m_connection);```

I get the message "Could not get read & write endpoints".

I discovered that in your code in the file CdsAsmSerialDriver.jac there is a check on line 187.
```
 if (dataInterfaceCount == mPortNumber) {
     mDataInterface = usbInterface;
}
```

  mPortNumber= 0, when the number of dataInterfaceCount = 0, usbInterface has ID = 1 (#1 on screenshot)
This interface has no endpoints. 
I need an interface with ID = 3 (#4 on screenshot).

I removed these lines from the code and I got my desired interface, but it's wrong. This will not work with any other device.

How can the library be adapted to work with a composite device?

![3839c084-00bc-444d-abb8-4669081b1e8c](https://github.com/mik3y/usb-serial-for-android/assets/35957335/8d15f592-76a5-4fb7-89fa-9c9c73b06873)

**Comment by kai-morich** [comment]
#1 with 0 endpoints looks strange. Does the device work with Windows?
How many ports are returned by `driver.getPorts()`

**Comment by diamond-61** [comment]
driver.getPorts() return 1 port

**Comment by diamond-61** [comment]
Add scrennshot with interface #0
![2](https://github.com/mik3y/usb-serial-for-android/assets/35957335/ef3353bc-91bf-4d31-9220-119202e83b71)

**Comment by kai-morich** [comment]
If you are not using usb-serial-for-android library version >= 3.6.0, you have to upgrade.
If you already use it, please send logcat output from CdcAcmSerialDriver  class

**Comment by diamond-61** [comment]
```
dependencies {
 implementation 'com.github.mik3y:usb-serial-for-android:3.7.0'
}
```

**Comment by diamond-61** [comment]
![Снимок экрана от 2023-11-27 14-27-22](https://github.com/mik3y/usb-serial-for-android/assets/35957335/b0adaa96-0121-4d6a-9adb-7b17d65eeaec)

**Comment by diamond-61** [comment]
![3](https://github.com/mik3y/usb-serial-for-android/assets/35957335/34916f69-8b78-4b85-8fb0-f72a3897d44d)

**Comment by kai-morich** [comment]
the library tries to detect the related interfaces with IAD, but the first row 12 01 00 ... does not match the [spec table 1-1](https://www.usb.org/sites/default/files/iadclasscode_r10.pdf)
