### ISSUE TITLE
Read the prompt

### ISSUE THREAD

**Issue by tonnqueiroz** [mik3y/usb-serial-for-android#550]
Is it possible to read the returned prompt before or after sending each command?

**Comment by kai-morich** [comment]
Not clear to me, what you are looking for. You can use direct read or event driven read as mentioned in [readme](https://github.com/mik3y/usb-serial-for-android)

**Comment by tonnqueiroz** [comment]
@kai-morich I need to automate the sending of commands to routers from several different manufacturers. Below I illustrate the prompts for routers manufactured by HUAWEI. Based on each prompt, my automation should send a different command, so I need to be able to read the prompt!

New Username:
Password:
Confirm password:
Username:
Password:
<Huawei>
[Huawei]

**Comment by kai-morich** [comment]
read the response with direct read or event driven read as mentioned in [readme](https://github.com/mik3y/usb-serial-for-android), then send different next command

**Comment by Uditk2002** [comment]
Hi @kai-morich @tonnqueiroz  direct read.. is mentioned inside the read() method, if I am right. Even if I call read() as soon as I write it reads 0 bytes. I tried adding delay but still, each and every command that is sent one at a time is recieved or may be appended (late) in the textbox after everything is sent!! . I have the same goal as @tonnqueiroz does.
I am a newbie to android programming. Your help would really mean a lot.
Thankyou

**Comment by Uditk2002** [comment]
Hi @kai-morich @tonnqueiroz direct read.. is mentioned inside the read() method, if I am right. Even if I call read() as soon as I write it reads 0 bytes. I tried adding delay but still, each and every command that is sent one at a time is recieved or may be appended (late) in the textbox after everything is sent!! . I have the same goal as @tonnqueiroz does.
I am a newbie to android programming. Your help would really mean a lot.
Thankyou

**Comment by kai-morich** [comment]
see https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#user-content-When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time
