### ISSUE TITLE
How to return complete data while read a message ?

### ISSUE THREAD

**Issue by HarizahSyawal** [mik3y/usb-serial-for-android#552]
Hello, i have do some integration for vending machine using mdb protocol and i'm using this library to communicated with. My issue here is whenever i read response from vending machine, it return line by line and the message not completed read in one line.
![WhatsApp Image 2023-11-27 at 23 29 33_c91f6b8f](https://github.com/mik3y/usb-serial-for-android/assets/37772347/c2f57e8b-6ff7-4e06-9178-c2ef631c59c2)

it supposed to be like this : 
![WhatsApp Image 2023-11-28 at 11 34 34_63489c40](https://github.com/mik3y/usb-serial-for-android/assets/37772347/17610fcc-525e-4e02-8196-fd1829685f53)

Here is my code : 

` private void receivedMessage(ArrayDeque<byte[]> datas) {

        char STX = '\u0002'; // Start of Text
        char ETX = '\u0003'; // End of Text
        SpannableStringBuilder spn = new SpannableStringBuilder();

        for (byte[] data : datas) {
            String msg = new String(data);
            String messageWithoutSTXETX = msg.replace(STX, ' ').replace(ETX, ' ');
            spn.append(messageWithoutSTXETX);
        }
        mTvReceiveText.append(TextUtil.newline_crlf+spn);
        Log.d(TAG,"FINAL MESSAGE "+spn);

        if (String.valueOf(spn).contains("1300") || String.valueOf(spn).startsWith("1300")) {
            handleReceivedMessage(String.valueOf(spn).trim());
        }
        else {
            Log.d(TAG, "not indicate a Vend Request : ");
        }
    }`

**Comment by kai-morich** [comment]
see https://github.com/mik3y/usb-serial-for-android/wiki/FAQ#user-content-When_reading_a_message_why_dont_all_bytes_arrive_at_the_same_time

**Comment by HarizahSyawal** [comment]
it mean,  i should limit the bytes follow my protocol specs right

**Comment by HarizahSyawal** [comment]
just now i have try your suggestion based on wiki that you share. The issue is whenever i put breakpoint, let say on the loop while read a messages it return completely but when i run without debug or get breakpoint the messages come out separately.

**Comment by kai-morich** [comment]
with debugging you change timing and therefore buffering behavior. Better use logcat output for analysis
