### ISSUE TITLE
UsbRequest queue(buffer, length) is was deprecated in API level 26

### ISSUE THREAD

**Issue by joshua-smith4** [mik3y/usb-serial-for-android#553]
In `CommonUsbSerialPort.java` in the `read` function there is a call to UsbRequest.queue with both the buffer and length parameters. Unfortunately this method was deprecated in API level 26. I am quite confident that removing the length parameter from the call will avoid the deprecated method overload and behave functionally the same. I'll provide a merge request and link to this issue.

https://github.com/mik3y/usb-serial-for-android/blob/573c7e41ca687a26293fd111b18df7cf40dd3cd1/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/CommonUsbSerialPort.java#L209

**Comment by kai-morich** [comment]
queue with single argument was added with API level 26. Moving to that function would break the library for older APIs.
If the method really gets removed, a version switch can be added, but for now lets keep as is
