### ISSUE TITLE
"No Driver For Device" Error

### ISSUE THREAD

**Issue by sharkboy777** [mik3y/usb-serial-for-android#557]
Getting the "No Driver for Device" error in React Native while trying to open the port.

I tried running the Java code in Android Studio, and the app shows a USB device list, but the first one has "no driver" as its name, and the click action is not working. There is one more showing in USB Devices, even though I have only connected one USB, but that was not showing any files at all when I opened it. 

Both vendorId and productId are available for these, but they are unable to open the port.
I couldn't find any details regarding these error codes in the code. No description or possible solutions for it are mentioned anywhere.

Please help me out.

**Comment by kai-morich** [comment]
see https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices
