### ISSUE TITLE
Using #include "USB.h" causes the device to not be found

### ISSUE THREAD

**Issue by 0cococ** [mik3y/usb-serial-for-android#567]
#include "USB.h"
void setup() {
 USB.begin();
}
 

After importing and initializing USB, val drivers = UsbSerialProber.getDefaultProber().findAllDrivers(manager) will not be able to find the device. Delete #include "USB.h" and USB.begin(); before it can work normally. Please help to find out what the problem is.
![image](https://github.com/mik3y/usb-serial-for-android/assets/108533707/84965e77-28bb-498b-b203-b5bbd9f849af)
![image](https://github.com/mik3y/usb-serial-for-android/assets/108533707/76c09a55-5733-4d55-b90c-25b69a5eef00)

**Comment by kai-morich** [comment]
please ask Arduino experts
