### ISSUE TITLE
How to send Ctrl+D command?

### ISSUE THREAD

**Issue by tonnqueiroz** [mik3y/usb-serial-for-android#568]
Hi,

How to send Ctrl+D command, please?

**Comment by kai-morich** [comment]
you can use a macro in HEX mode. Ctrl+D is '04'

**Comment by tonnqueiroz** [comment]
I need to send it directly from the command line, that is, without creating a macro! Is it possible?

**Comment by kai-morich** [comment]
depends on your commandline. what are you using?

**Comment by tonnqueiroz** [comment]
I'm using a .json file where the script on each line is similar to sending a command through a "Serial USB Terminal"!

**Comment by kai-morich** [comment]
\u0004 inside a json string should be ctrl+d
