### ISSUE TITLE
Best Way to Get Supported Baud Rates?

### ISSUE THREAD

**Issue by HTRamsey** [mik3y/usb-serial-for-android#586]
I see standard baud rates are private in one of the drivers but that's it

**Comment by kai-morich** [comment]
The usual baud rates are supported by all devices. 
For very high or low baud rates you have to try, as the limits are in many cases not documented by the vendors.
For very high baud rates (>1MBit?) you also have to be prepared data loss issues, e.g. when your Android app is not reading fast enough.
