### ISSUE TITLE
Build failing to find v3.3.0

### ISSUE THREAD

**Issue by nickmesibov** [mik3y/usb-serial-for-android#592]
Our app has been using v3.3.0 for a couple of years with no issues, but the build is no longer able to find v3.3.0 and we get the following error when building:

'Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform usb-serial-for-android-3.3.0.aar (com.github.mik3y:usb-serial-for-android:3.3.0) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find usb-serial-for-android-3.3.0.jar (com.github.mik3y:usb-serial-for-android:3.3.0).
        Searched in the following locations:
            https://jitpack.io/com/github/mik3y/usb-serial-for-android/3.3.0/usb-serial-for-android-3.3.0.aar
            https://jitpack.io/com/github/mik3y/usb-serial-for-android/3.3.0/usb-serial-for-android-3.3.0.jar'

Downgrading the version number to 3.2.0 is able to build with no issues

**Comment by kai-morich** [comment]
Looks like jitpack sometimes looses files, e.g. https://github.com/jitpack/jitpack.io/issues/3295

I clicked around in jitpack UI. Now the files are back.
