### ISSUE TITLE
Only reading zeros from CdcAcmSerialDriver

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#6]
_From [mafish...@gmail.com](https://code.google.com/u/115220808713786216606/) on December 18, 2012 09:07:23_

What steps will reproduce the problem? 1. Connect /dev/ttyACM0 device
2. cat /dev/tty/ACM0 and watch serial traffic
3. Use the usb-serial-for-android API and read only 0's for bytes What is the expected output? What do you see instead? Data other than 0's. What version of the product are you using? On what operating system? ICS 4.1.x Please provide any additional information below. I can see traffic by cat'ing the /dev/ttvACM0 device and by using the app "android-serialport-api" to do the same.  However, when using this library, all I am reading is 0's.  When the CdcAcmSerialDriver reads, it always reads the correct amount of data (never less than 0), but the bytes returned in the buffer are 0.

_Original issue: http://code.google.com/p/usb-serial-for-android/issues/detail?id=6_

**Comment by mindentropy** [comment]
@marlonscalabrin 

I am also having the same problem with a Tiva MCU. Could please provide the complete modified code you put in open(..) method?

**Comment by marlonscalabrin** [comment]
I only verify all "endpoints" looking for the correct type.
And selecting the "in point" and the "out point".
Do it in the open() method in CdcAcmSerialDriver.java.
You need add your vendorID and productID in UsbId.java.
And add its reference on CdcAcmSerialDriver.java#getSupportedDevices().


Att, []s
Marlon Henrique Scalabrin
*invent.to <http://invent.to> - Soluções em Sistemas Computacionais*

2015-08-18 8:16 GMT-03:00 mindentropy <notifications@github.com>:
