### ISSUE TITLE
FTDI FT2232 doesn't seem to work

### ISSUE THREAD

**Issue by GozzoMan** [mik3y/usb-serial-for-android#66]
Hello, first of all thanks for the project.

I've been able to correctly communicate with a FT232R (product id 0x6001), but NOT with a FT2232 (product id 0x6010).

Adding 0x6010 in UsbId.java and getSupportedDevices() in FtdiSerialDriver.java, I've been able to get a reference with UsbSerialProber.findAllDevices() and then open(), but then communication doesn't seem to work.

The exact FT2232 device I'm using is:  http://www.tincantools.com/JTAG/Flyswatter.html
I'm correctly able to use it by other code (Python on PC).

Thank you.

**Comment by mik3y** [comment]
Closing old troubleshooting issue. Consider the [the google group](https://github.com/mik3y/usb-serial-for-android#help--discussion) for further discussion.
