### ISSUE TITLE
Ainol tablet and 3DR radio cannot connect

### ISSUE THREAD

**Issue by alextel69** [mik3y/usb-serial-for-android#72]
I am DroidPlanner dev (https://github.com/DroidPlanner). Project uses your library to communicate with 3DR radio kit.
I use micro-usb-to-micro-usb OTG cable to connect radio to Samsung Galaxy S2 ( Android 4.4.4 Cyanogenmod) and it works ok.
But when I connect radio to Ainol Numy 3G AX10 (Android 4.2), radio is not recognized. It's chipset is MediaTek MT8389.

3DR radio set - https://store.3drobotics.com/products/3dr-radio

When I connected blue connector of OTG cable to Ainol and normal one to S2, I successfully copied files from S2. But when I changed direction, S2 did not discover Ainol.

**Comment by mik3y** [comment]
Closing old troubleshooting issue. Consider the [the google group](https://github.com/mik3y/usb-serial-for-android#help--discussion) for further discussion.
