### ISSUE TITLE
Does usb-serial-for-android works with ESC/POS printer through OTG?

### ISSUE THREAD

**Issue by ymike** [mik3y/usb-serial-for-android#75]
Hello to all,
I need to print to a _generic_ ESC/POS thermal printer
So not using a specific vendor library (like Custom, Epson, StarIO...) but with a generic library capable to connect/print to almost any ESC/POS printers connected to an android tablet using USB OTG cable connection.
Is usb-serial-for-android the right library for this kind of work, or am I on the wrong direction?
Any suggestion is appriciated.

Many thanks.
Y.Mike

**Comment by soulsoft-dz** [comment]
Hi , i have the same issue , @ymike did you find any solutions ??? , @mik3y  thanks for the library , but can u provide me any post for the generic driver  to implement printer specific protocols ??,

**Comment by tomeroto** [comment]
Hi @ymike, I have the same issue, my printer not detect on list of devices. I was plug the cable to usb serial or com serial (rs232), but no luck. Please help me.
