### ISSUE TITLE
Support multiple serial ports

### ISSUE THREAD

**Issue by bj0** [mik3y/usb-serial-for-android#80]
The code looks like it assumes there is a single serial port on the usb device and grabs the first interface.  This is fine for most commerical usb->serial adapters, but if you have a custom device (PIC) that implements a USB Composite device, you can have multiple interfaces that each provide a serial port.

There is probably not a lot of demand for this, but I have such a device and would love to use this library.

**Comment by kai-morich** [comment]
FT4232H is supported with 61b272b8b6e087f0bc9b065eef1e7baf66412fa7

the correct endpoint for CDC/ACM composite device is used with 608c67499a10ccf5c25811e9d1611187192aaa45. Are there really devices with multiple serial (USB_CLASS_CDC_DATA) interfaces?

**Comment by kai-morich** [comment]
multiple ports are supported for ftdi and cp210X
