### ISSUE TITLE
Problems with CDC devices (Infineon XMC4500)

### ISSUE THREAD

**Issue by Uveder** [mik3y/usb-serial-for-android#81]
Hi, I am using Infineon XMC4500, and it provides some functions for communication using CDC, so to make your driver work with it, I changed the device filter and something more in part of the code. Then finally it recognizes the device and open the driver, but it receives only the first frame and afterwards it stops working, the App is not closed, but even the microprocessor is sending some frames to the android-device, it doesn't read messages anymore. Any possible solution to solve it even it is using CDC for the communication?

**Comment by njprogramming** [comment]
Hello all,

I had a similar sort of issue with an Atmel CDC device, It's hard to say if it is the way the device was configured or the actual driver implementation itself. However for my situation the endpoints were swapped with the driver trying to read from the writing endpoint and vice versa. I can do some additional testing and @mik3y I can send through a pull request for future reference if required as I've implemented additional features such as get line coding and class verification.

Regardless great project, keep up the good work.

Nicholas

**Comment by kai-morich** [comment]
please try latest version which supports swapped endpoints

**Comment by widavies** [comment]
@Uveder What vendor id and product id did you use? I can't get my Android phone to even detect an XMC 4700 that's connected. Any other tips?

**Comment by kai-morich** [comment]
CDC-ACM devices are detecte by USB interface properties, the VID/PID is irrelevant since recent library versions
if not detected it may not offer CDC-ACM endpoints or power supply is to weak or ...
