### ISSUE TITLE
wiki is not up to date ....

### ISSUE THREAD

**Issue by courdi95** [mik3y/usb-serial-for-android#86]
Hello

I am trying to use Wiki (https://github.com/mik3y/usb-serial-for-android/wiki/Building-From-Source)  to build from sources, but is it not compatible with Eclipse.

I have great trouble to use it with Android Studio.... could you help ?

**Comment by w8jcik** [comment]
The simplest solution is to download the last commit before conversion to the Android Studio, and import project to the Eclipse. For this commit, the Wiki is correct
https://github.com/mik3y/usb-serial-for-android/tree/9c577949b0c56fd3cc14b6df5a457a8647ad91c4
