### ISSUE TITLE
listening or polling ? that is the question ... 

### ISSUE THREAD

**Issue by courdi95** [mik3y/usb-serial-for-android#87]
Hello 

I am using today USB/serial cables with Prolific PL2303HXD chip and also some cables with FTDI FT232R chip.

With such cables, I am also using Android drivers provided by Prolific and FTDI : samples provided by the manufacturers are based on polling processing, with threads or runnables. When I are using such cables on PCs, I am familiar with interrupt processing, so I am wondering if it would be possible to have such interrupt processing on Android. 

So I have a dummy question : how can I have listener processing on Android ? Is the usb-serial-for-android library useful for such idea ? if yes, how ?

**Comment by MRodriguess** [comment]
Yes you can register a listener when registering a new SerialInputPutputManager.Listener you have to override a method called onNewData(); This can be your listener.

I am using it this way and it works, as long as you keep your SerialInputPutputManager.Listener alive.

**Comment by mik3y** [comment]
Looks like this is resolved.
