### ISSUE TITLE
cannot resolve method getPort(int)

### ISSUE THREAD

**Issue by juancrescente** [mik3y/usb-serial-for-android#90]
I'm getting this error in Android Studio in this line: 

UsbSerialPort port = driver.getPort(0);

"cannot resolve method getPort(int)"

**Comment by dmitryzakharov1** [comment]
Same issue

**Comment by dmitryzakharov1** [comment]
//UsbSerialPort port = driver.getPort(0);
List<UsbSerialPort> myPortList = driver.getPorts();
UsbSerialPort port = myPortList.get(0);

**Comment by kai-morich** [comment]
use latest library
