### ISSUE TITLE
hang on read, error on write  - SOLVED

### ISSUE THREAD

**Issue by mikecarr** [mik3y/usb-serial-for-android#91]
I have setup my project with the same code that is in your sample, however if I try to send data I get an error or if I try to read from the port I received no data and it just hangs. Nexus 7 running 5.0.0 and S4 running 4.4.4

```
                    UsbManager manager = (UsbManager) getSystemService(Context.USB_SERVICE);
                    HashMap<String, UsbDevice> deviceList = manager.getDeviceList();


                    // Probe for our custom CDC devices, which use VID 0x20A0
                    // and PIDS 0x415E and 0x415A.
                    ProbeTable customTable = new ProbeTable();
                    customTable.addProduct(0x20A0, 0x415E, CdcAcmSerialDriver.class);


                    UsbSerialProber prober = new UsbSerialProber(customTable);


                    List<UsbSerialDriver> availableDrivers = prober.findAllDrivers(manager);
                    if (availableDrivers.isEmpty()) {


                        return;
                    }


                    // Open a connection to the first available driver.
                    UsbSerialDriver driver = availableDrivers.get(0);
                    UsbDeviceConnection connection = manager.openDevice(driver.getDevice());
                    if (connection == null) {
                        // You probably need to call UsbManager.requestPermission(driver.getDevice(), ..)
                        return;
                    }




                    // Read some data! Most have just one port (port 0).
                    mPort = driver.getPorts().get(0);
                    mPort.open(connection);
                    mPort.setParameters(19200, UsbSerialPort.DATABITS_8, UsbSerialPort.STOPBITS_1, UsbSerialPort.PARITY_NONE);
                    mPort.setDTR(true);
                    //mPort.setRTS(true);


                    byte TXbuffer[] = new byte[20];
                    byte RXbuffer[] = new byte[20];


                    int no = mPort.write(TXbuffer, 1000);
                    android.os.SystemClock.sleep(500);
                    int numBytesRead = mPort.read(RXbuffer, 1000);
                    mPort.close();
```

D/UsbHostManager(  623): Added device UsbDevice[mName=/dev/bus/usb/001/003,mVendorId=8352,mProductId=16734,mClass=239,mSubclass=2,mProtocol=1,mManufacturerName=openpilot.org,mProductName=Revolution,mSerialNumber=43002C000C47333231343239+FW,mConfigurations=[
D/UsbHostManager(  623): UsbConfiguration[mId=1,mName=null,mAttributes=192,mMaxPower=125,mInterfaces=[
D/UsbHostManager(  623): UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=2,mSubclass=2,mProtocol=1,mEndpoints=[
D/UsbHostManager(  623): UsbEndpoint[mAddress=130,mAttributes=3,mMaxPacketSize=32,mInterval=4]]
D/UsbHostManager(  623): UsbInterface[mId=1,mAlternateSetting=0,mName=null,mClass=10,mSubclass=0,mProtocol=0,mEndpoints=[
D/UsbHostManager(  623): UsbEndpoint[mAddress=131,mAttributes=2,mMaxPacketSize=64,mInterval=0]
D/UsbHostManager(  623): UsbEndpoint[mAddress=3,mAttributes=2,mMaxPacketSize=64,mInterval=0]]
D/UsbHostManager(  623): UsbInterface[mId=2,mAlternateSetting=0,mName=null,mClass=3,mSubclass=0,mProtocol=0,mEndpoints=[
D/UsbHostManager(  623): UsbEndpoint[mAddress=129,mAttributes=3,mMaxPacketSize=64,mInterval=4]
D/UsbHostManager(  623): UsbEndpoint[mAddress=1,mAttributes=3,mMaxPacketSize=64,mInterval=4]]]]

D/CdcAcmSerialDriver(25537): claiming interfaces, count=3
D/CdcAcmSerialDriver(25537): Control iface=UsbInterface[mId=0,mAlternateSetting=0,mName=null,mClass=2,mSubclass=2,mProtocol=1,mEndpoints=[
D/CdcAcmSerialDriver(25537): UsbEndpoint[mAddress=130,mAttributes=3,mMaxPacketSize=32,mInterval=4]]
D/CdcAcmSerialDriver(25537): Control endpoint direction: 128
D/CdcAcmSerialDriver(25537): Claiming data interface.
D/CdcAcmSerialDriver(25537): data iface=UsbInterface[mId=1,mAlternateSetting=0,mName=null,mClass=10,mSubclass=0,mProtocol=0,mEndpoints=[
D/CdcAcmSerialDriver(25537): UsbEndpoint[mAddress=131,mAttributes=2,mMaxPacketSize=64,mInterval=0]
D/CdcAcmSerialDriver(25537): UsbEndpoint[mAddress=3,mAttributes=2,mMaxPacketSize=64,mInterval=0]]
D/CdcAcmSerialDriver(25537): Read endpoint direction: 0
D/CdcAcmSerialDriver(25537): Write endpoint direction: 128
D/CdcAcmSerialDriver(25537): Async reads enabled

Exception is thrown here
int no = mPort.write(TXbuffer, 1000);

java.io.IOException: Error writing 20 bytes at offset 0 length=20

If I comment that out, it hangs here:
int numBytesRead = mPort.read(RXbuffer, 1000);

any ideas?

•••

**Comment by tonyctsiu** [comment]
how was it solved?

**Comment by andremacpereira** [comment]
How did you managed to solve that?

**Comment by mikecarr** [comment]
We have the endpoints reversed (TX and RX and RX was TX)

**Comment by andremacpereira** [comment]
Thank you. I've got it to work too. :-)

**Comment by andremacpereira** [comment]
Could you please share what did you modify in the code?

**Comment by mikecarr** [comment]
https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java#L129
from: mReadEndpoint = mDataInterface.getEndpoint(1);
to: mReadEndpoint = mDataInterface.getEndpoint(0);

https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java#L131
from: mWriteEndpoint = mDataInterface.getEndpoint(0);
to: mWriteEndpoint = mDataInterface.getEndpoint(1);

**Comment by andremacpereira** [comment]
Well, that's odd. It seems like it send/receive bytes only if we have both endpoints on "1"

**Comment by sureshjoshi** [comment]
I also had to set both to 1 to get a 'successful' transfer. I don't know if it's actually successful, or just outputs a successful log statement. 

When using it with the original setup, I would get errors on write occasionally.

**Comment by kai-morich** [comment]
with 608c67499a10ccf5c25811e9d1611187192aaa45 CDC endpoints are determined by type, not position any more

**Comment by JairajJangleSLIOT** [comment]
I am getting the same error `java.io.IOException: Error writing 6 bytes at offset 0 length=6` when I try to `serialPort.write(msg, timeOut)` on my USB device which is Arduino which is directly connected via USB so no question of improper connection. After `serialPort.open(connection)` here is what I have done with setParameter:

```
serialPort.setParameters(
    BAUD_RATE, /* 9600 */
    8,
    UsbSerialPort.STOPBITS_1,
    UsbSerialPort.PARITY_NONE
)
serialPort.dtr = true
serialPort.rts = true
```

I do not understand what changing endpoint means. If someone can give a clear explanation fo what exactly to do to solve the issue, it would be great.
