### ISSUE TITLE
File Transfer

### ISSUE THREAD

**Issue by ndvalkov** [mik3y/usb-serial-for-android#93]
Hello,

I am trying to implement XMODEM file transfer in my app. Can you, please, tell me if I need to modify the lib source, for example, add classes for InputStream/OutputStream and somehow attach them to a driver/port, or I can use the port.read() port.write() directly?

Thanks.

**Comment by youxikaifa** [comment]
Error:Application and test application id cannot be the same: both are 'com.hoho.android.usbserial.examples' for debugAndroidTest，what's wrong? anyone can help me？

**Comment by kai-morich** [comment]
file transfer and XMODEM specific flow control has to be implemented on top of this library, e.g. https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal
