### ISSUE TITLE
Quick Start info outdated

### ISSUE THREAD

**Issue by hubatish** [mik3y/usb-serial-for-android#95]
Still trying to build this package as part of an Eclipse project, been having a few issues, but overall the documentation is quite good.  Some exceptions:
The example code sample is outdated.  It was pretty simple to fix, driver.getPort() seems to be no longer supported, so I changed it to getPorts().get(0).  port.setBaudRate() is also out of date, and I replaced it with the appropriate port.setParameters code.  The import/linking instructions with eclipse are also outdated.  
These are relatively minor, but I bring it up because the code is generally quite well documented, and the quick start guide (even with errors) has been very helpful to me!
Unfortunately I'm now figuring out my cable may not be supported, still looking into it..

**Comment by mik3y** [comment]
Sorry about the mismatch between the latest `README.md` and the old release. Follow #131 for the next release.
