### ISSUE TITLE
Get Default Prober method not available

### ISSUE THREAD

**Issue by GaryDoo** [mik3y/usb-serial-for-android#97]
Hi, 
I've just linked the latest jar v0.1.0 into the project and I'm trying to use the getDefaultProber() method that should be contained with the UsbSerialProber class but it's not available for use.  It's present in the repository code but not in the jar.

I'm trying to connect with a Japanese thermal printer so I'm pretty sure that this is important to trying to establish drivers etc.

If anyone has any tips I'd appreciate hearing thme

**Comment by cpbridges** [comment]
Also have this issue during the .jar.

**Comment by jubeira** [comment]
@GaryDoo @cpbridges the released version 0.1.0 is pretty old, and the API has changed since then.
You can either build the library from source and use the latest methods (I would do that), or go back to that release and check how the usage was before.

**Comment by kai-morich** [comment]
use latest library
