### ISSUE TITLE
availableDrivers is empty

### ISSUE THREAD

**Issue by chackor** [mik3y/usb-serial-for-android#99]
This lines returns an empty list. 
            List<UsbSerialDriver> availableDrivers = UsbSerialProber.getDefaultProber().findAllDrivers(manager);

please advice how to address this.

Thanks,
R

**Comment by victordiaz** [comment]
I have the same issue with some devices. It works for me with Arduino based ones, but not with mbed.
So far I know is not a Android issue since other USB monitoring apps can detect my device. 

Any idea?

Cheers

**Comment by xiiaoleii** [comment]
me too. the result is: 0 device(s) found.

**Comment by jonathanEp1** [comment]
Me too. did anyone solve this one?

**Comment by hrshs** [comment]
https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices

**Comment by kai-morich** [comment]
use custom prober as mentioned in previous comment
